# F1 Driver Elo Standings by Season

One cell per season (1980–present). Each cell queries `driver_elo_season_summary` for that year and shows the drivers ordered by end-of-season Elo rating, alongside their championship points and finishing position.

Run `python -m elo_f1.elo.run_elo` first if `data/elo_f1.db` is stale.

In [1]:
import sqlite3
import pandas as pd

DB_PATH = "data/elo_f1.db"


def elo_standings(year: int) -> pd.DataFrame:
    conn = sqlite3.connect(DB_PATH)
    try:
        df = pd.read_sql_query(
            """
            SELECT
                d.given_name || ' ' || d.family_name AS driver,
                c.name AS constructor,
                s.elo_season_end,
                s.elo_season_average,
                s.points,
                s.final_points_position,
                s.races_started
            FROM driver_elo_season_summary s
            JOIN drivers d ON d.driver_id = s.driver_id
            JOIN constructors c ON c.constructor_id = s.constructor_id
            WHERE s.year = ?
            ORDER BY s.elo_season_end DESC
            """,
            conn,
            params=(year,),
        )
    finally:
        conn.close()
    df.index = range(1, len(df) + 1)
    df.index.name = "elo_rank"
    return df

## 1980

In [2]:
elo_standings(1980)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,Carlos Reutemann,Williams,1534.599368,1513.258519,42.0,3.0,14
2,Alan Jones,Williams,1534.235545,1516.241911,67.0,1.0,14
3,Nelson Piquet,Brabham,1532.760152,1526.642607,54.0,2.0,14
4,Jacques Laffite,Ligier,1513.073970,1511.297144,34.0,4.0,14
5,René Arnoux,Renault,1510.930904,1508.423232,29.0,6.0,14
6,Didier Pironi,Ligier,1504.902305,1503.911573,32.0,5.0,14
7,Jean-Pierre Jabouille,Renault,1504.375836,1497.930789,9.0,8.0,13
8,Patrick Depailler,Alfa Romeo,1500.000000,1500.000000,0.0,NaN,8
9,Nigel Mansell,Team Lotus,1500.000000,1500.000000,0.0,NaN,2
10,Tiff Needell,Ensign,1500.000000,1500.000000,0.0,NaN,1
11,Rupert Keegan,Williams,1491.772197,1494.933543,0.0,NaN,4
12,John Watson,McLaren,1491.653031,1492.629902,6.0,11.0,13
13,Jan Lammers,ATS,1490.495314,1496.015037,0.0,NaN,6
14,Gilles Villeneuve,Ferrari,1489.514809,1496.386392,6.0,14.0,14
15,Hector Rebaque,Brabham,1488.934412,1490.373915,1.0,21.0,7
16,Geoff Lees,Shadow,1487.187500,1493.593750,0.0,NaN,2
17,Clay Regazzoni,Ensign,1486.172285,1495.664267,0.0,NaN,4
18,Andrea de Cesaris,Alfa Romeo,1485.254237,1492.627119,0.0,NaN,2
19,Mike Thackwell,Tyrrell,1485.000000,1485.000000,0.0,NaN,1
20,Eddie Cheever,Osella,1482.180671,1484.692663,0.0,NaN,10
21,Marc Surer,ATS,1475.006775,1485.004307,0.0,NaN,10
22,Vittorio Brambilla,Alfa Romeo,1472.687500,1479.937500,0.0,NaN,2
23,Emerson Fittipaldi,Fittipaldi,1471.137556,1487.181275,5.0,15.0,14
24,Keke Rosberg,Fittipaldi,1469.578327,1482.002796,6.0,10.0,11
25,Jochen Mass,Arrows,1467.972023,1478.631162,4.0,17.0,12
26,Mario Andretti,Team Lotus,1466.501163,1472.603320,1.0,20.0,14
27,Alain Prost,McLaren,1465.803507,1475.524058,5.0,16.0,13
28,Ricardo Zunino,Brabham,1463.249850,1475.653180,0.0,NaN,6
29,Jody Scheckter,Ferrari,1454.333150,1479.599239,2.0,19.0,13
30,Bruno Giacomelli,Alfa Romeo,1449.786798,1469.557712,4.0,18.0,14
31,Elio de Angelis,Team Lotus,1446.061191,1462.155685,13.0,7.0,14
32,Derek Daly,Tyrrell,1441.520178,1479.754425,6.0,12.0,14
33,Riccardo Patrese,Arrows,1440.543864,1478.346153,7.0,9.0,14
34,Jean-Pierre Jarier,Tyrrell,1434.428277,1454.102585,6.0,13.0,14

## 1981

In [3]:
elo_standings(1981)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,Carlos Reutemann,Williams,1533.338531,1537.232683,49.0,2.0,15
2,John Watson,McLaren,1524.236400,1510.173816,27.0,6.0,15
3,Nelson Piquet,Brabham,1523.162002,1510.740438,50.0,1.0,15
4,Jacques Laffite,Ligier,1517.374201,1505.411630,44.0,4.0,15
5,Alan Jones,Williams,1501.744678,1488.744441,46.0,3.0,15
6,Alain Prost,Renault,1500.404327,1486.669834,43.0,5.0,15
7,Jean-Pierre Jabouille,Ligier,1500.000000,1500.000000,0.0,NaN,3
8,Ricardo Londoño,Ensign,1500.000000,1500.000000,0.0,NaN,1
9,Derek Warwick,Toleman,1500.000000,1500.000000,0.0,NaN,1
10,Elio de Angelis,Team Lotus,1499.461406,1494.135071,14.0,8.0,15
11,Piercarlo Ghinzani,Osella,1494.046812,1494.046812,0.0,NaN,1
12,Brian Henton,Toleman,1493.408314,1493.408314,0.0,NaN,1
13,Keke Rosberg,Fittipaldi,1491.228548,1499.841160,0.0,NaN,9
14,Ricardo Zunino,Tyrrell,1489.029162,1491.978957,0.0,NaN,2
15,Jan Lammers,ATS,1487.412267,1489.129011,0.0,NaN,3
16,Eddie Cheever,Tyrrell,1487.299998,1497.066121,10.0,12.0,14
17,Riccardo Patrese,Arrows,1485.225441,1502.601019,10.0,11.0,15
18,Miguel Ángel Guerra,Osella,1485.000000,1485.000000,0.0,NaN,1
19,Derek Daly,March,1483.697934,1489.695430,0.0,NaN,8
20,Chico Serra,Fittipaldi,1482.607147,1483.349646,0.0,NaN,6
21,Beppe Gabbiani,Osella,1480.020833,1482.493056,0.0,NaN,3
22,Didier Pironi,Ferrari,1479.716980,1487.480823,9.0,13.0,15
23,Marc Surer,Theodore,1478.728276,1489.552335,4.0,16.0,13
24,Mario Andretti,Alfa Romeo,1477.885366,1488.509838,3.0,17.0,15
25,Jean-Pierre Jarier,Osella,1471.680105,1484.376608,0.0,NaN,9
26,Gilles Villeneuve,Ferrari,1470.646019,1498.777506,25.0,7.0,15
27,Nigel Mansell,Team Lotus,1469.106701,1479.422495,8.0,14.0,14
28,Bruno Giacomelli,Alfa Romeo,1463.472893,1469.569352,7.0,15.0,15
29,Slim Borgudd,ATS,1462.854581,1484.248455,1.0,20.0,7
30,Eliseo Salazar,Ensign,1455.229969,1476.641802,1.0,21.0,9
31,René Arnoux,Renault,1451.307307,1476.839438,11.0,9.0,14
32,Michele Alboreto,Tyrrell,1445.361538,1463.378269,0.0,NaN,10
33,Siegfried Stohr,Arrows,1442.845458,1459.164726,0.0,NaN,9
34,Patrick Tambay,Ligier,1436.248134,1480.135554,1.0,19.0,14
35,Hector Rebaque,Brabham,1433.251178,1453.818782,11.0,10.0,14
36,Andrea de Cesaris,McLaren,1404.350320,1453.968844,1.0,18.0,15

## 1982

In [4]:
elo_standings(1982)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,Keke Rosberg,Williams,1550.572340,1521.421968,44.0,1.0,15
2,Patrick Tambay,Ferrari,1515.252317,1503.041847,25.0,7.0,8
3,Michele Alboreto,Tyrrell,1513.543208,1508.722019,25.0,8.0,16
4,Didier Pironi,Ferrari,1513.295698,1509.289380,39.0,2.0,12
5,Niki Lauda,McLaren,1511.093730,1500.497532,30.0,5.0,14
6,Eddie Cheever,Ligier,1509.584261,1506.912957,15.0,12.0,14
7,Alain Prost,Renault,1505.404920,1501.090062,34.0,4.0,16
8,Elio de Angelis,Team Lotus,1504.572860,1496.442159,23.0,9.0,15
9,Carlos Reutemann,Williams,1501.348188,1505.514854,6.0,16.0,2
10,Jan Lammers,Theodore,1500.000000,1500.000000,0.0,NaN,1
11,Riccardo Paletti,Osella,1500.000000,1500.000000,0.0,NaN,3
12,John Watson,McLaren,1492.391935,1501.431863,39.0,3.0,15
13,Nelson Piquet,Brabham,1492.292429,1484.943978,20.0,11.0,14
14,Teo Fabi,Toleman,1490.000000,1492.857143,0.0,NaN,7
15,Marc Surer,Arrows,1487.719867,1490.478113,3.0,21.0,12
16,Rupert Keegan,March,1486.693158,1491.345636,0.0,NaN,3
17,Geoff Lees,Theodore,1485.922310,1487.961155,0.0,NaN,2
18,Mario Andretti,Ferrari,1484.359818,1484.620721,4.0,19.0,3
19,Jochen Mass,March,1483.845121,1502.135535,0.0,NaN,9
20,Tommy Byrne,Theodore,1477.938462,1483.488462,0.0,NaN,2
21,Jacques Laffite,Ligier,1477.834826,1480.577225,5.0,18.0,15
22,Derek Warwick,Toleman,1474.880442,1485.220580,0.0,NaN,11
23,Slim Borgudd,Tyrrell,1474.518845,1483.182830,0.0,NaN,3
24,Nigel Mansell,Team Lotus,1469.810154,1492.988540,7.0,14.0,13
25,Riccardo Patrese,Brabham,1468.653027,1482.124024,21.0,10.0,15
26,Gilles Villeneuve,Ferrari,1463.988736,1480.845029,6.0,15.0,5
27,Chico Serra,Fittipaldi,1462.016726,1481.856956,1.0,26.0,9
28,Roberto Guerrero,Ensign,1461.320242,1471.443049,0.0,NaN,9
29,Andrea de Cesaris,Alfa Romeo,1461.067320,1474.528277,5.0,17.0,16
30,Bruno Giacomelli,Alfa Romeo,1453.689723,1477.265216,2.0,22.0,16
31,Jean-Pierre Jarier,Osella,1453.500312,1476.319682,3.0,20.0,14
32,Manfred Winkelhock,ATS,1450.637952,1468.765728,2.0,24.0,13
33,Brian Henton,Tyrrell,1449.376872,1478.412272,0.0,NaN,14
34,René Arnoux,Renault,1443.572189,1454.387580,28.0,6.0,16
35,Mauro Baldi,Arrows,1441.286870,1468.807274,2.0,25.0,11
36,Raul Boesel,March,1433.189089,1453.340700,0.0,NaN,10
37,Eliseo Salazar,ATS,1426.137562,1469.682865,2.0,23.0,13
38,Derek Daly,Williams,1420.235605,1452.915540,8.0,13.0,15

## 1983

In [5]:
elo_standings(1983)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,René Arnoux,Ferrari,1543.146465,1513.281054,49.0,3.0,15
2,Alain Prost,Renault,1537.442641,1524.453353,57.0,2.0,15
3,Nelson Piquet,Brabham,1527.780656,1516.197311,59.0,1.0,15
4,Patrick Tambay,Ferrari,1514.959215,1517.830243,40.0,4.0,15
5,Riccardo Patrese,Brabham,1509.150017,1496.502977,13.0,9.0,15
6,Keke Rosberg,Williams,1507.492468,1498.144043,27.0,5.0,15
7,Eddie Cheever,Renault,1504.931110,1503.359400,22.0,7.0,15
8,Alan Jones,Arrows,1500.000000,1500.000000,0.0,NaN,1
9,Andrea de Cesaris,Alfa Romeo,1498.558067,1501.606691,15.0,8.0,14
10,Derek Warwick,Toleman,1497.692875,1487.060814,9.0,14.0,15
11,Eliseo Salazar,RAM,1495.460435,1495.460435,0.0,NaN,2
12,Jonathan Palmer,Williams,1495.010810,1495.010810,0.0,NaN,1
13,Kenny Acheson,RAM,1494.653679,1494.653679,0.0,NaN,1
14,Stefan Johansson,Spirit,1492.090710,1496.828288,0.0,NaN,6
15,Piercarlo Ghinzani,Osella,1489.189442,1493.822538,0.0,NaN,7
16,Corrado Fabi,Osella,1488.739657,1490.495863,0.0,NaN,10
17,Thierry Boutsen,Arrows,1488.471035,1500.403027,0.0,NaN,10
18,Chico Serra,Arrows,1485.642353,1488.751894,0.0,NaN,4
19,Nigel Mansell,Team Lotus,1481.693217,1486.821352,10.0,13.0,15
20,Elio de Angelis,Team Lotus,1481.453219,1485.972143,2.0,18.0,15
21,Johnny Cecotto,Theodore,1476.929738,1486.044214,1.0,20.0,9
22,John Watson,McLaren,1476.296188,1498.415674,22.0,6.0,14
23,Raul Boesel,Ligier,1475.013113,1488.649953,0.0,NaN,13
24,Jacques Laffite,Williams,1472.777171,1496.093916,11.0,11.0,13
25,Roberto Guerrero,Theodore,1465.245288,1485.577410,0.0,NaN,13
26,Danny Sullivan,Tyrrell,1464.803341,1484.606868,2.0,17.0,15
27,Marc Surer,Arrows,1464.525040,1483.947125,4.0,15.0,15
28,Niki Lauda,McLaren,1464.302845,1475.170646,12.0,10.0,14
29,Michele Alboreto,Tyrrell,1462.133623,1473.234910,10.0,12.0,15
30,Mauro Baldi,Alfa Romeo,1458.213579,1461.698690,3.0,16.0,15
31,Jean-Pierre Jarier,Ligier,1456.560380,1471.610968,0.0,NaN,15
32,Manfred Winkelhock,ATS,1455.758592,1466.625462,0.0,NaN,14
33,Bruno Giacomelli,Toleman,1453.386779,1470.207409,1.0,19.0,14

## 1984

In [6]:
elo_standings(1984)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,Elio de Angelis,Team Lotus,1531.077333,1520.451769,34.0,3.0,16
2,Alain Prost,McLaren,1524.636436,1509.959793,71.5,2.0,16
3,Niki Lauda,McLaren,1521.144212,1513.927416,72.0,1.0,16
4,Michele Alboreto,Ferrari,1520.554759,1505.749675,30.5,4.0,16
5,Nelson Piquet,Brabham,1518.509853,1504.307989,29.0,5.0,16
6,Keke Rosberg,Williams,1505.295028,1512.297326,20.5,8.0,16
7,Corrado Fabi,Brabham,1503.928600,1501.309533,0.0,NaN,3
8,Philippe Streiff,Renault,1500.000000,1500.000000,0.0,NaN,1
9,Mike Thackwell,RAM,1500.000000,1500.000000,0.0,NaN,1
10,René Arnoux,Ferrari,1494.193814,1504.159689,27.0,6.0,16
11,Huub Rothengatter,Spirit,1489.087520,1495.667599,0.0,NaN,7
12,Teo Fabi,Brabham,1483.535907,1487.390613,9.0,12.0,12
13,Mauro Baldi,Spirit,1482.590079,1493.194678,0.0,NaN,7
14,Stefan Johansson,Tyrrell,1478.173937,1484.950031,3.0,17.0,6
15,Ayrton Senna,Toleman,1478.100797,1492.116626,13.0,9.0,14
16,Gerhard Berger,ATS,1478.004181,1489.454927,0.0,NaN,4
17,Patrick Tambay,Renault,1473.691461,1478.235490,11.0,11.0,15
18,Thierry Boutsen,Arrows,1473.669052,1485.084403,5.0,15.0,15
19,Derek Warwick,Renault,1473.453258,1491.090136,23.0,7.0,16
20,Jacques Laffite,Williams,1472.965923,1484.070515,5.0,14.0,16
21,Riccardo Patrese,Alfa Romeo,1472.806856,1480.672784,8.0,13.0,16
22,Jo Gartner,Osella,1471.094143,1477.800455,0.0,NaN,8
23,Martin Brundle,Tyrrell,1470.035861,1482.687830,0.0,NaN,7
24,Jonathan Palmer,RAM,1464.160567,1474.650163,0.0,NaN,14
25,Piercarlo Ghinzani,Osella,1460.558375,1481.459863,2.0,19.0,15
26,Johnny Cecotto,Toleman,1459.223476,1486.882601,0.0,NaN,9
27,Eddie Cheever,Alfa Romeo,1458.912699,1482.865113,3.0,16.0,15
28,Andrea de Cesaris,Ligier,1458.553148,1475.370379,3.0,18.0,16
29,Philippe Alliot,RAM,1457.684708,1480.081970,0.0,NaN,13
30,Manfred Winkelhock,ATS,1446.321799,1475.867301,0.0,NaN,14
31,Nigel Mansell,Team Lotus,1442.803561,1465.504489,13.0,10.0,16
32,Stefan Bellof,Tyrrell,1429.310087,1462.395081,0.0,NaN,12
33,Marc Surer,Arrows,1424.791203,1457.259412,1.0,20.0,15
34,François Hesnault,Ligier,1416.707442,1458.614711,0.0,NaN,15

## 1985

In [7]:
elo_standings(1985)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,Michele Alboreto,Ferrari,1555.109907,1541.628377,53.0,2.0,16
2,Alain Prost,McLaren,1531.572610,1510.284290,73.0,1.0,16
3,Nigel Mansell,Williams,1513.709074,1497.174799,31.0,6.0,16
4,Ayrton Senna,Team Lotus,1513.318014,1498.297189,38.0,4.0,16
5,Nelson Piquet,Brabham,1509.900715,1504.977158,21.0,8.0,16
6,Elio de Angelis,Team Lotus,1508.661429,1517.457045,33.0,5.0,16
7,Keke Rosberg,Williams,1503.595234,1494.260288,40.0,3.0,16
8,Kenny Acheson,RAM,1500.000000,1500.000000,0.0,NaN,2
9,Christian Danner,Zakspeed,1500.000000,1500.000000,0.0,NaN,2
10,Alan Jones,Lola,1500.000000,1500.000000,0.0,NaN,4
11,René Arnoux,Ferrari,1498.059162,1498.059162,3.0,19.0,1
12,Teo Fabi,Toleman,1496.216909,1498.544965,0.0,NaN,13
13,Jonathan Palmer,Zakspeed,1494.518687,1495.889015,0.0,NaN,8
14,John Watson,McLaren,1492.730804,1492.730804,0.0,NaN,1
15,Huub Rothengatter,Osella,1489.344286,1493.934030,0.0,NaN,7
16,Ivan Capelli,Tyrrell,1488.580055,1488.990028,3.0,18.0,2
17,Thierry Boutsen,Arrows,1487.858752,1501.361384,11.0,11.0,16
18,Mauro Baldi,Spirit,1487.126866,1491.417910,0.0,NaN,3
19,François Hesnault,Brabham,1486.106557,1486.106557,0.0,NaN,4
20,Stefan Bellof,Tyrrell,1485.639475,1493.036024,4.0,16.0,9
21,Jacques Laffite,Ligier,1483.684972,1493.901783,16.0,9.0,15
22,Niki Lauda,McLaren,1480.990288,1488.606972,14.0,10.0,14
23,Derek Warwick,Renault,1476.650673,1479.760331,5.0,14.0,15
24,Marc Surer,Brabham,1474.242058,1480.837829,5.0,13.0,12
25,Philippe Streiff,Ligier,1473.973194,1488.369166,4.0,15.0,5
26,Manfred Winkelhock,RAM,1471.863608,1479.377559,0.0,NaN,8
27,Eddie Cheever,Alfa Romeo,1470.602111,1491.603534,0.0,NaN,16
28,Riccardo Patrese,Alfa Romeo,1456.166582,1472.893749,0.0,NaN,16
29,Patrick Tambay,Renault,1454.492492,1478.102708,11.0,12.0,15
30,Stefan Johansson,Ferrari,1445.985128,1469.140296,26.0,7.0,16
31,Martin Brundle,Tyrrell,1442.170471,1462.260379,0.0,NaN,15
32,Andrea de Cesaris,Ligier,1442.153722,1465.807246,3.0,17.0,11
33,Piercarlo Ghinzani,Osella,1440.561834,1463.306724,0.0,NaN,14
34,Philippe Alliot,RAM,1437.028957,1462.692110,0.0,NaN,13
35,Gerhard Berger,Arrows,1433.836404,1449.055158,3.0,20.0,16
36,Pierluigi Martini,Minardi,1426.275309,1461.384992,0.0,NaN,15

## 1986

In [8]:
elo_standings(1986)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,Ayrton Senna,Team Lotus,1543.692973,1531.504601,55.0,4.0,16
2,Nigel Mansell,Williams,1538.581979,1515.987875,70.0,2.0,16
3,Nelson Piquet,Williams,1537.044791,1513.647848,69.0,3.0,16
4,Alain Prost,McLaren,1536.736103,1528.180547,72.0,1.0,16
5,René Arnoux,Ligier,1512.300552,1504.355111,14.0,10.0,16
6,Alex Caffi,Osella,1500.000000,1500.000000,0.0,NaN,1
7,Ivan Capelli,AGS,1500.000000,1500.000000,0.0,NaN,2
8,Eddie Cheever,Lola,1500.000000,1500.000000,0.0,NaN,1
9,Keke Rosberg,McLaren,1498.894631,1495.281140,22.0,6.0,16
10,Elio de Angelis,Brabham,1497.236429,1497.236429,0.0,NaN,4
11,Stefan Johansson,Ferrari,1496.179009,1493.638245,23.0,5.0,16
12,Thierry Boutsen,Arrows,1494.563883,1493.520276,0.0,NaN,16
13,Philippe Alliot,Ligier,1493.175046,1497.081914,1.0,19.0,7
14,Andrea de Cesaris,Minardi,1490.552748,1498.047509,0.0,NaN,15
15,Gerhard Berger,Benetton,1489.743194,1494.352836,17.0,7.0,16
16,Jacques Laffite,Ligier,1488.874743,1503.857620,14.0,8.0,9
17,Teo Fabi,Benetton,1484.794688,1491.766168,2.0,16.0,16
18,Riccardo Patrese,Brabham,1482.866261,1498.426872,2.0,17.0,16
19,Michele Alboreto,Ferrari,1478.280283,1496.342198,14.0,9.0,16
20,Huub Rothengatter,Zakspeed,1477.878912,1485.383396,0.0,NaN,12
21,Marc Surer,Arrows,1476.898544,1489.287730,0.0,NaN,5
22,Martin Brundle,Tyrrell,1474.665024,1486.897601,8.0,11.0,16
23,Allen Berg,Osella,1473.199812,1485.234602,0.0,NaN,9
24,Piercarlo Ghinzani,Osella,1470.321760,1484.182253,0.0,NaN,15
25,Philippe Streiff,Tyrrell,1460.960311,1474.629771,3.0,14.0,16
26,Alan Jones,Lola,1459.808673,1466.578663,4.0,12.0,16
27,Christian Danner,Arrows,1459.186573,1485.978571,1.0,18.0,15
28,Jonathan Palmer,Zakspeed,1454.635240,1473.441035,0.0,NaN,16
29,Derek Warwick,Brabham,1453.030306,1470.237095,0.0,NaN,11
30,Johnny Dumfries,Team Lotus,1449.592298,1461.371164,3.0,13.0,15
31,Alessandro Nannini,Minardi,1448.320951,1476.115710,0.0,NaN,15
32,Patrick Tambay,Lola,1421.529592,1461.756282,2.0,15.0,15

## 1987

In [9]:
elo_standings(1987)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,Nelson Piquet,Williams,1546.099924,1531.135444,73.0,1.0,16
2,Ayrton Senna,Team Lotus,1537.361989,1520.627634,57.0,3.0,16
3,Alain Prost,McLaren,1535.628219,1532.444419,46.0,4.0,16
4,Nigel Mansell,Williams,1527.137117,1510.352185,61.0,2.0,15
5,Gerhard Berger,Ferrari,1519.702968,1502.551773,36.0,5.0,16
6,Eddie Cheever,Arrows,1515.050466,1507.680598,8.0,10.0,16
7,Riccardo Patrese,Brabham,1511.471050,1506.207111,6.0,13.0,16
8,Thierry Boutsen,Benetton,1501.137942,1500.147513,16.0,8.0,16
9,Alex Caffi,Osella,1500.000000,1500.000000,0.0,NaN,14
10,Franco Forini,Osella,1500.000000,1500.000000,0.0,NaN,2
11,Nicola Larini,Coloni,1500.000000,1500.000000,0.0,NaN,1
12,Stefano Modena,Brabham,1500.000000,1500.000000,0.0,NaN,1
13,Gabriele Tarquini,Osella,1500.000000,1500.000000,0.0,NaN,1
14,Michele Alboreto,Ferrari,1499.639529,1496.786821,17.0,7.0,16
15,Teo Fabi,Benetton,1499.198638,1496.002963,12.0,9.0,16
16,Roberto Moreno,AGS,1495.500244,1497.750122,1.0,21.0,2
17,Martin Brundle,Zakspeed,1491.476329,1498.950156,2.0,18.0,16
18,Stefan Johansson,McLaren,1487.456484,1492.050143,30.0,6.0,16
19,Yannick Dalmas,Larrousse,1485.178458,1486.767287,0.0,NaN,3
20,Alessandro Nannini,Minardi,1482.113278,1498.074685,0.0,NaN,16
21,René Arnoux,Ligier,1481.068341,1494.059232,1.0,20.0,15
22,Piercarlo Ghinzani,Ligier,1480.643480,1485.075488,0.0,NaN,15
23,Derek Warwick,Arrows,1463.288547,1483.555519,3.0,16.0,16
24,Andrea de Cesaris,Brabham,1462.172068,1483.718620,4.0,14.0,16
25,Christian Danner,Zakspeed,1454.735598,1482.154867,0.0,NaN,16
26,Pascal Fabre,AGS,1453.971799,1469.335042,0.0,NaN,11
27,Jonathan Palmer,Tyrrell,1450.665194,1468.059601,7.0,11.0,16
28,Ivan Capelli,March,1446.062151,1480.960680,1.0,19.0,16
29,Adrián Campos,Minardi,1444.273452,1467.612957,0.0,NaN,16
30,Satoru Nakajima,Team Lotus,1442.281130,1473.353752,7.0,12.0,16
31,Philippe Alliot,Larrousse,1435.496998,1467.415470,3.0,17.0,15
32,Philippe Streiff,Tyrrell,1407.509335,1457.218802,4.0,15.0,16

## 1988

In [10]:
elo_standings(1988)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,Alain Prost,McLaren,1568.366691,1537.174769,87.0,2.0,16
2,Ayrton Senna,McLaren,1547.827201,1518.464819,90.0,1.0,16
3,Gerhard Berger,Ferrari,1533.595993,1531.968820,41.0,3.0,16
4,Thierry Boutsen,Benetton,1524.940763,1512.397601,27.0,4.0,16
5,Ivan Capelli,March,1509.489077,1498.168623,17.0,7.0,16
6,Riccardo Patrese,Williams,1506.751905,1501.353285,8.0,11.0,16
7,Jonathan Palmer,Tyrrell,1502.456191,1501.040277,5.0,14.0,14
8,Bernd Schneider,Zakspeed,1502.249847,1501.499898,0.0,NaN,6
9,Nelson Piquet,Team Lotus,1502.152894,1502.279064,22.0,6.0,16
10,Yannick Dalmas,Larrousse,1498.838309,1498.924532,0.0,NaN,13
11,Martin Brundle,Williams,1498.735854,1498.735854,0.0,NaN,1
12,Stefan Johansson,Ligier,1496.628872,1496.007790,0.0,NaN,10
13,Michele Alboreto,Ferrari,1492.322808,1496.691305,24.0,5.0,16
14,Eddie Cheever,Arrows,1491.895018,1492.223163,6.0,12.0,16
15,Oscar Larrauri,Euro Brun,1491.099428,1495.737863,0.0,NaN,8
16,Jean-Louis Schlesser,Williams,1490.817459,1490.817459,0.0,NaN,1
17,Nicola Larini,Osella,1489.385972,1493.728243,0.0,NaN,11
18,Adrián Campos,Minardi,1489.283079,1494.641540,0.0,NaN,2
19,Aguri Suzuki,Larrousse,1488.539815,1488.539815,0.0,NaN,1
20,Piercarlo Ghinzani,Zakspeed,1487.576759,1493.443771,0.0,NaN,9
21,Alessandro Nannini,Benetton,1485.668918,1499.412283,12.0,10.0,16
22,Luis Pérez-Sala,Minardi,1484.371929,1496.146530,0.0,NaN,14
23,Andrea de Cesaris,Rial,1483.846502,1493.752347,3.0,15.0,16
24,Gabriele Tarquini,Coloni,1482.478555,1493.291172,0.0,NaN,8
25,Derek Warwick,Arrows,1481.991236,1493.459133,17.0,8.0,16
26,Philippe Streiff,AGS,1478.251483,1490.478861,0.0,NaN,16
27,Maurício Gugelmin,March,1470.504973,1491.687538,5.0,13.0,16
28,Pierluigi Martini,Minardi,1470.500146,1480.157034,1.0,17.0,9
29,Stefano Modena,Euro Brun,1469.916205,1487.107107,0.0,NaN,12
30,Nigel Mansell,Williams,1456.642832,1483.638887,12.0,9.0,14
31,Alex Caffi,Dallara,1455.284804,1474.154036,0.0,NaN,14
32,Julian Bailey,Tyrrell,1453.023466,1472.610085,0.0,NaN,6
33,Satoru Nakajima,Team Lotus,1448.025764,1478.162430,1.0,16.0,14
34,Philippe Alliot,Larrousse,1444.294734,1463.423775,0.0,NaN,16
35,René Arnoux,Ligier,1442.032493,1472.640531,0.0,NaN,14

## 1989

In [11]:
elo_standings(1989)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,Alain Prost,McLaren,1535.447289,1525.160452,76.0,1.0,16
2,Ayrton Senna,McLaren,1525.833315,1524.678315,60.0,2.0,16
3,Thierry Boutsen,Williams,1524.566515,1509.605629,37.0,5.0,16
4,Alessandro Nannini,Benetton,1523.603100,1512.810566,32.0,6.0,16
5,Riccardo Patrese,Williams,1509.990704,1504.980155,40.0,3.0,16
6,Nigel Mansell,Ferrari,1505.839003,1514.220734,38.0,4.0,15
7,Jean Alesi,Tyrrell,1505.512615,1502.876093,8.0,9.0,8
8,Stefan Johansson,Onyx,1500.189617,1496.534588,6.0,12.0,8
9,Paolo Barilla,Minardi,1500.000000,1500.000000,0.0,NaN,1
10,Yannick Dalmas,Larrousse,1500.000000,1500.000000,0.0,NaN,1
11,Jyrki Järvilehto,Onyx,1500.000000,1500.000000,0.0,NaN,2
12,Roberto Moreno,Coloni,1500.000000,1500.000000,0.0,NaN,4
13,Pierre-Henri Raphanel,Coloni,1500.000000,1500.000000,0.0,NaN,1
14,Éric Bernard,Larrousse,1497.627294,1497.627294,0.0,NaN,2
15,Bernd Schneider,Zakspeed,1492.950820,1492.950820,0.0,NaN,2
16,Volker Weidler,Rial,1492.800000,1492.800000,0.0,NaN,1
17,Piercarlo Ghinzani,Osella,1492.142857,1497.380952,0.0,NaN,3
18,Maurício Gugelmin,March,1490.892499,1501.513365,4.0,16.0,15
19,Martin Donnelly,Arrows,1488.606664,1488.606664,0.0,NaN,1
20,Christian Danner,Rial,1486.110996,1491.981770,3.0,22.0,4
21,Pierluigi Martini,Minardi,1485.121020,1492.493633,5.0,15.0,15
22,Michele Alboreto,Tyrrell,1484.433459,1496.711149,6.0,13.0,10
23,Nicola Larini,Osella,1484.379876,1485.414358,0.0,NaN,8
24,Gabriele Tarquini,AGS,1483.297692,1492.852247,1.0,27.0,6
25,Olivier Grouillard,Ligier,1480.516076,1491.477930,1.0,26.0,12
26,Bertrand Gachot,Onyx,1478.395393,1489.554659,0.0,NaN,5
27,Martin Brundle,Brabham,1478.143381,1495.843952,4.0,20.0,14
28,Andrea de Cesaris,Dallara,1467.962490,1487.763100,4.0,17.0,15
29,Nelson Piquet,Team Lotus,1466.255826,1486.379728,12.0,8.0,15
30,Ivan Capelli,March,1464.056960,1472.930508,0.0,NaN,16
31,Stefano Modena,Brabham,1461.919456,1477.171346,4.0,18.0,16
32,Derek Warwick,Arrows,1459.259116,1491.766956,7.0,10.0,15
33,Alex Caffi,Dallara,1457.075884,1486.368618,4.0,19.0,14
34,Johnny Herbert,Benetton,1455.527510,1484.124950,5.0,14.0,6
35,Eddie Cheever,Arrows,1450.921140,1473.025860,6.0,11.0,14
36,Philippe Alliot,Larrousse,1449.744770,1472.297674,1.0,29.0,15
37,Jonathan Palmer,Tyrrell,1449.246820,1473.978983,2.0,25.0,15
38,Gerhard Berger,Ferrari,1446.370872,1459.236938,21.0,7.0,15
39,Emanuele Pirro,Benetton,1444.965986,1468.747496,2.0,23.0,10
40,René Arnoux,Ligier,1444.311642,1472.299429,2.0,24.0,9
41,Satoru Nakajima,Team Lotus,1438.286284,1463.227083,3.0,21.0,13
42,Luis Pérez-Sala,Minardi,1413.894527,1456.324868,1.0,28.0,12

## 1990

In [12]:
elo_standings(1990)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,Ayrton Senna,McLaren,1556.970120,1543.072523,78.0,1.0,16
2,Nelson Piquet,Benetton,1541.547188,1513.851258,43.0,3.0,16
3,Alain Prost,Ferrari,1536.836558,1524.682900,71.0,2.0,16
4,Thierry Boutsen,Williams,1532.475928,1517.846623,34.0,6.0,16
5,Nigel Mansell,Ferrari,1516.245983,1502.081014,37.0,5.0,16
6,Riccardo Patrese,Williams,1510.920973,1502.815348,23.0,7.0,16
7,Éric Bernard,Larrousse,1503.553703,1499.389801,5.0,13.0,16
8,Johnny Herbert,Team Lotus,1500.000000,1500.000000,0.0,NaN,2
9,Derek Warwick,Team Lotus,1498.849596,1497.749306,3.0,14.0,16
10,Gabriele Tarquini,AGS,1495.907811,1496.930859,0.0,NaN,4
11,Gerhard Berger,McLaren,1494.588094,1507.367196,43.0,4.0,16
12,Maurício Gugelmin,Leyton House,1494.322839,1495.158368,1.0,18.0,12
13,Jyrki Järvilehto,Onyx,1494.078896,1494.078896,0.0,NaN,5
14,Bernd Schneider,Arrows,1489.922012,1489.922012,0.0,NaN,1
15,Yannick Dalmas,AGS,1489.169626,1494.333937,0.0,NaN,5
16,Ivan Capelli,Leyton House,1484.184233,1487.671123,6.0,10.0,14
17,Roberto Moreno,Euro Brun,1483.975877,1491.599312,6.0,11.0,5
18,Gianni Morbidelli,Minardi,1482.769158,1489.215732,0.0,NaN,3
19,Jean Alesi,Tyrrell,1481.445423,1505.058429,13.0,9.0,16
20,Alex Caffi,Arrows,1478.630705,1493.949806,2.0,16.0,11
21,Stefano Modena,Brabham,1477.316788,1494.206657,2.0,17.0,16
22,Nicola Larini,Ligier,1474.941045,1482.206687,0.0,NaN,16
23,Alessandro Nannini,Benetton,1473.252342,1482.765257,21.0,8.0,14
24,Martin Donnelly,Team Lotus,1471.940038,1482.063165,0.0,NaN,14
25,David Brabham,Brabham,1470.684921,1489.567166,0.0,NaN,8
26,Paolo Barilla,Minardi,1469.114023,1492.678892,0.0,NaN,8
27,Olivier Grouillard,Osella,1465.933346,1477.575611,0.0,NaN,9
28,Gregor Foitek,Onyx,1460.627869,1476.973668,0.0,NaN,7
29,Aguri Suzuki,Larrousse,1458.529140,1479.184668,6.0,12.0,16
30,Pierluigi Martini,Minardi,1456.373841,1471.514679,0.0,NaN,16
31,Michele Alboreto,Arrows,1449.342137,1474.691594,0.0,NaN,13
32,Emanuele Pirro,Dallara,1448.893086,1464.514979,0.0,NaN,14
33,Andrea de Cesaris,Dallara,1445.325730,1474.662478,0.0,NaN,15
34,Satoru Nakajima,Tyrrell,1425.463884,1454.616492,3.0,15.0,16
35,Philippe Alliot,Ligier,1395.570707,1455.921933,0.0,NaN,15

## 1991

In [13]:
elo_standings(1991)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,Ayrton Senna,McLaren,1584.860024,1549.898402,96.0,1.0,16
2,Nigel Mansell,Williams,1530.360740,1518.298107,72.0,2.0,16
3,Stefano Modena,Tyrrell,1526.273334,1515.534845,10.0,8.0,16
4,Nelson Piquet,Benetton,1520.557047,1509.093938,26.5,6.0,16
5,Alain Prost,Ferrari,1511.514819,1501.900436,34.0,5.0,15
6,Gerhard Berger,McLaren,1508.655995,1494.583331,43.0,4.0,16
7,Maurício Gugelmin,Leyton House,1507.694357,1500.703976,0.0,NaN,16
8,Andrea de Cesaris,Jordan,1506.567941,1507.134057,9.0,9.0,15
9,Riccardo Patrese,Williams,1505.825842,1495.532053,53.0,3.0,16
10,Stefan Johansson,Footwork,1500.000000,1500.000000,0.0,NaN,1
11,Eric van de Poele,Lambo,1500.000000,1500.000000,0.0,NaN,1
12,Michele Alboreto,Footwork,1499.003668,1498.920012,0.0,NaN,9
13,Olivier Grouillard,Fondmetal,1495.400426,1497.700213,0.0,NaN,4
14,Michael Schumacher,Benetton,1494.766747,1505.461788,4.0,14.0,6
15,Julian Bailey,Team Lotus,1491.761794,1491.761794,1.0,23.0,1
16,Alessandro Zanardi,Jordan,1491.159608,1495.247039,0.0,NaN,3
17,Éric Bernard,Lola,1486.888500,1497.134026,1.0,21.0,13
18,Gabriele Tarquini,AGS,1485.930966,1492.656360,0.0,NaN,5
19,Alex Caffi,Footwork,1485.789386,1490.252510,0.0,NaN,2
20,Johnny Herbert,Team Lotus,1483.801536,1483.865451,0.0,NaN,7
21,Emanuele Pirro,Dallara,1479.646197,1495.078781,1.0,18.0,13
22,Érik Comas,Ligier,1478.780545,1480.390555,0.0,NaN,13
23,Aguri Suzuki,Lola,1474.849078,1481.707812,1.0,22.0,12
24,Martin Brundle,Brabham,1470.716105,1484.285597,2.0,17.0,14
25,Jean Alesi,Ferrari,1470.530371,1487.641261,21.0,7.0,16
26,Jyrki Järvilehto,Dallara,1470.077962,1488.057145,4.0,12.0,16
27,Karl Wendlinger,Leyton House,1469.815149,1474.485755,0.0,NaN,2
28,Roberto Moreno,Benetton,1462.962806,1480.259114,8.0,10.0,14
29,Mark Blundell,Brabham,1461.891938,1467.086627,1.0,19.0,14
30,Gianni Morbidelli,Minardi,1460.875642,1475.004030,0.5,24.0,16
31,Nicola Larini,Lambo,1460.268837,1477.946614,0.0,NaN,5
32,Bertrand Gachot,Jordan,1454.718608,1479.969294,4.0,13.0,10
33,Pierluigi Martini,Minardi,1447.147229,1473.105363,6.0,11.0,16
34,Mika Häkkinen,Team Lotus,1444.493097,1479.858471,2.0,16.0,15
35,Ivan Capelli,Leyton House,1444.407118,1474.310437,1.0,20.0,14
36,Thierry Boutsen,Ligier,1427.470314,1480.710668,0.0,NaN,16
37,Satoru Nakajima,Tyrrell,1382.459647,1439.544283,2.0,15.0,16

## 1992

In [14]:
elo_standings(1992)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,Nigel Mansell,Williams,1585.241448,1562.631870,108.0,1.0,16
2,Gerhard Berger,McLaren,1526.670187,1505.804031,49.0,5.0,16
3,Michael Schumacher,Benetton,1523.164320,1513.568756,53.0,3.0,16
4,Mika Häkkinen,Team Lotus,1513.406562,1498.872712,11.0,8.0,15
5,Ayrton Senna,McLaren,1511.697340,1510.754045,50.0,4.0,16
6,Martin Brundle,Benetton,1510.458310,1492.395036,38.0,6.0,16
7,Michele Alboreto,Footwork,1506.919362,1503.587651,6.0,10.0,16
8,Jean Alesi,Ferrari,1502.260809,1505.505028,18.0,7.0,16
9,Perry McCarthy,Andrea Moda,1500.000000,1500.000000,0.0,NaN,1
10,Roberto Moreno,Andrea Moda,1500.000000,1500.000000,0.0,NaN,1
11,Alessandro Zanardi,Minardi,1500.000000,1500.000000,0.0,NaN,1
12,Jan Lammers,March,1494.724824,1497.362412,0.0,NaN,2
13,Érik Comas,Ligier,1490.999357,1497.255676,4.0,11.0,16
14,Jyrki Järvilehto,Dallara,1488.933497,1488.056676,0.0,NaN,15
15,Damon Hill,Brabham,1487.587769,1490.584126,0.0,NaN,2
16,Andrea de Cesaris,Tyrrell,1487.227418,1491.030555,8.0,9.0,16
17,Nicola Larini,Ferrari,1484.376491,1488.346360,0.0,NaN,2
18,Emanuele Naspetti,March,1481.718002,1486.418581,0.0,NaN,5
19,Christian Fittipaldi,Minardi,1481.364494,1481.364155,1.0,18.0,10
20,Gabriele Tarquini,Fondmetal,1479.559779,1490.392814,0.0,NaN,13
21,Karl Wendlinger,March,1478.536879,1491.585108,3.0,12.0,14
22,Eric van de Poele,Fondmetal,1478.530637,1484.816649,0.0,NaN,5
23,Paul Belmondo,March,1478.525181,1479.089383,0.0,NaN,5
24,Riccardo Patrese,Williams,1476.946040,1484.346143,56.0,2.0,16
25,Stefano Modena,Jordan,1467.205939,1480.396132,1.0,17.0,12
26,Andrea Chiesa,Fondmetal,1461.560201,1475.714047,0.0,NaN,3
27,Gianni Morbidelli,Minardi,1454.595987,1480.551865,0.0,NaN,15
28,Ukyo Katayama,Larrousse,1446.083246,1464.706050,0.0,NaN,14
29,Ivan Capelli,Ferrari,1440.085650,1453.832967,3.0,13.0,14
30,Bertrand Gachot,Larrousse,1436.093824,1471.894537,1.0,19.0,16
31,Maurício Gugelmin,Jordan,1430.253118,1471.860149,0.0,NaN,16
32,Aguri Suzuki,Footwork,1426.219602,1456.932926,0.0,NaN,14
33,Thierry Boutsen,Ligier,1425.081244,1454.726095,2.0,14.0,16
34,Johnny Herbert,Team Lotus,1419.438655,1458.020260,2.0,15.0,16
35,Pierluigi Martini,Dallara,1416.253514,1469.114117,2.0,16.0,16
36,Olivier Grouillard,Tyrrell,1411.849971,1469.072139,0.0,NaN,16

## 1993

In [15]:
elo_standings(1993)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,Ayrton Senna,McLaren,1558.703110,1543.028750,73.0,2.0,16
2,Alain Prost,Williams,1555.748141,1522.706074,99.0,1.0,16
3,Damon Hill,Williams,1541.689543,1520.061835,69.0,3.0,16
4,Michael Schumacher,Benetton,1528.538721,1509.233169,52.0,4.0,16
5,Jean Alesi,Ferrari,1509.526567,1505.153157,16.0,6.0,16
6,Emanuele Naspetti,Jordan,1500.000000,1500.000000,0.0,NaN,1
7,Karl Wendlinger,Sauber,1496.198962,1492.763777,7.0,12.0,16
8,Marco Apicella,Jordan,1490.000000,1490.000000,0.0,NaN,1
9,Mika Häkkinen,McLaren,1489.240708,1489.341223,4.0,15.0,3
10,Jean-Marc Gounon,Minardi,1488.227848,1494.113924,0.0,NaN,2
11,Érik Comas,Larrousse,1486.745532,1492.084276,1.0,21.0,16
12,Thierry Boutsen,Jordan,1486.114503,1493.437343,0.0,NaN,10
13,Ivan Capelli,Jordan,1485.208333,1485.208333,0.0,NaN,1
14,Toshio Suzuki,Larrousse,1481.290619,1487.669794,0.0,NaN,2
15,Eddie Irvine,Jordan,1479.697348,1486.679976,1.0,22.0,2
16,Martin Brundle,Ligier,1478.151093,1476.572644,13.0,7.0,16
17,Michele Alboreto,Lola,1477.229029,1488.463101,0.0,NaN,9
18,Johnny Herbert,Team Lotus,1475.766354,1498.587362,11.0,9.0,16
19,Pierluigi Martini,Minardi,1468.615635,1477.375984,0.0,NaN,8
20,Gerhard Berger,Ferrari,1468.359537,1480.717680,12.0,8.0,16
21,Pedro Lamy,Team Lotus,1462.447678,1482.834754,0.0,NaN,4
22,Christian Fittipaldi,Minardi,1461.031848,1485.200552,5.0,14.0,14
23,Rubens Barrichello,Jordan,1459.859028,1473.688016,2.0,18.0,16
24,Philippe Alliot,Larrousse,1458.131162,1473.605576,2.0,17.0,14
25,Luca Badoer,Lola,1457.586562,1477.370087,0.0,NaN,12
26,Andrea de Cesaris,Tyrrell,1455.290992,1476.865520,0.0,NaN,16
27,Riccardo Patrese,Benetton,1451.767153,1472.548735,20.0,5.0,16
28,Fabrizio Barbazza,Minardi,1450.535523,1465.813188,2.0,19.0,8
29,Alessandro Zanardi,Team Lotus,1445.187040,1465.151953,1.0,20.0,12
30,Derek Warwick,Footwork,1440.196339,1467.108952,4.0,16.0,16
31,Jyrki Järvilehto,Sauber,1435.772346,1472.350458,5.0,13.0,16
32,Ukyo Katayama,Tyrrell,1425.719908,1469.437075,0.0,NaN,16
33,Michael Andretti,McLaren,1417.670067,1436.584609,7.0,11.0,13
34,Aguri Suzuki,Footwork,1407.950991,1448.917422,0.0,NaN,16
35,Mark Blundell,Ligier,1396.269987,1443.322273,10.0,10.0,16

## 1994

In [16]:
elo_standings(1994)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,Michael Schumacher,Benetton,1555.908099,1543.842906,92.0,1.0,14
2,Damon Hill,Williams,1544.174097,1522.496764,91.0,2.0,16
3,Érik Comas,Larrousse,1538.287433,1516.626495,2.0,23.0,15
4,Mika Häkkinen,McLaren,1533.908991,1513.373956,26.0,4.0,15
5,Gerhard Berger,Ferrari,1527.904149,1516.941031,41.0,3.0,16
6,Olivier Panis,Ligier,1521.805335,1515.457943,9.0,11.0,16
7,David Brabham,Simtek,1513.355833,1502.622434,0.0,NaN,16
8,Johnny Herbert,Team Lotus,1504.999063,1514.440259,0.0,NaN,16
9,Heinz-Harald Frentzen,Sauber,1502.946686,1490.244921,7.0,13.0,16
10,Philippe Alliot,McLaren,1500.017663,1498.400319,0.0,NaN,2
11,Andrea Montermini,Simtek,1500.000000,1500.000000,0.0,NaN,1
12,Mika Salo,Team Lotus,1497.711963,1499.303971,0.0,NaN,2
13,Aguri Suzuki,Jordan,1497.085236,1497.085236,0.0,NaN,1
14,Jean-Denis Délétraz,Larrousse,1496.779414,1496.779414,0.0,NaN,1
15,Karl Wendlinger,Sauber,1493.648435,1494.952941,4.0,19.0,4
16,Domenico Schiattarella,Simtek,1493.404897,1494.798353,0.0,NaN,2
17,Jean Alesi,Ferrari,1489.755241,1501.655248,24.0,5.0,14
18,Bertrand Gachot,Pacific,1489.614322,1487.802771,0.0,NaN,5
19,Nigel Mansell,Williams,1486.625754,1484.471636,13.0,9.0,4
20,Christian Fittipaldi,Footwork,1484.095416,1488.207860,6.0,15.0,16
21,Yannick Dalmas,Larrousse,1483.832643,1485.293221,0.0,NaN,2
22,Paul Belmondo,Pacific,1483.688440,1491.844220,0.0,NaN,2
23,Jean-Marc Gounon,Simtek,1483.189453,1484.857251,0.0,NaN,7
24,Nicola Larini,Ferrari,1479.724742,1480.375770,6.0,14.0,2
25,Roland Ratzenberger,Simtek,1478.855125,1487.029411,0.0,NaN,2
26,Taki Inoue,Simtek,1478.053012,1478.053012,0.0,NaN,1
27,Hideki Noda,Larrousse,1477.627888,1483.088799,0.0,NaN,3
28,Rubens Barrichello,Jordan,1473.136166,1488.165663,19.0,6.0,16
29,Alessandro Zanardi,Team Lotus,1470.890047,1480.430942,0.0,NaN,10
30,Franck Lagorce,Ligier,1470.156794,1476.213938,0.0,NaN,2
31,Philippe Adams,Team Lotus,1469.518177,1474.769107,0.0,NaN,2
32,Ayrton Senna,Williams,1462.080783,1475.900169,0.0,NaN,3
33,Pedro Lamy,Team Lotus,1459.280721,1473.437482,0.0,NaN,4
34,Ukyo Katayama,Tyrrell,1455.396169,1494.974734,5.0,17.0,16
35,Olivier Beretta,Larrousse,1452.331948,1468.045033,0.0,NaN,10
36,David Coulthard,Williams,1452.091347,1472.323612,14.0,8.0,8
37,Gianni Morbidelli,Footwork,1451.924803,1480.948292,3.0,22.0,16
38,Pierluigi Martini,Minardi,1451.921157,1470.648681,4.0,21.0,16
39,Michele Alboreto,Minardi,1445.288519,1476.446518,1.0,25.0,16
40,Andrea de Cesaris,Sauber,1443.364223,1469.697916,4.0,20.0,11
41,Jyrki Järvilehto,Benetton,1435.451158,1461.480583,1.0,24.0,8
42,Eddie Irvine,Jordan,1434.512394,1459.775880,6.0,16.0,13
43,Martin Brundle,McLaren,1429.834543,1468.205758,16.0,7.0,16
44,Mark Blundell,Tyrrell,1425.820815,1449.269270,8.0,12.0,16
45,Jos Verstappen,Benetton,1424.803536,1447.707333,10.0,10.0,10
46,Éric Bernard,Ligier,1421.647256,1444.390104,4.0,18.0,14

## 1995

In [17]:
elo_standings(1995)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,Heinz-Harald Frentzen,Sauber,1565.100695,1541.233046,15.0,9.0,17
2,Michael Schumacher,Benetton,1536.861690,1525.318235,102.0,1.0,17
3,Mika Salo,Tyrrell,1527.223515,1506.430888,5.0,15.0,17
4,Gerhard Berger,Ferrari,1519.821522,1506.405792,31.0,6.0,17
5,Mika Häkkinen,McLaren,1519.311310,1514.686912,17.0,7.0,16
6,Gianni Morbidelli,Footwork,1512.472256,1513.718159,5.0,14.0,10
7,Jos Verstappen,Simtek,1511.455221,1508.656100,0.0,NaN,5
8,Eddie Irvine,Jordan,1505.651563,1502.702544,10.0,12.0,17
9,Pierluigi Martini,Minardi,1498.431362,1497.028846,0.0,NaN,9
10,Pedro Lamy,Minardi,1497.931662,1498.161461,1.0,18.0,8
11,Jean-Denis Délétraz,Pacific,1491.561938,1494.141989,0.0,NaN,2
12,Bertrand Gachot,Pacific,1490.911484,1495.118506,0.0,NaN,11
13,Gabriele Tarquini,Tyrrell,1489.583741,1489.583741,0.0,NaN,1
14,Jan Magnussen,McLaren,1489.066228,1489.066228,0.0,NaN,1
15,Nigel Mansell,McLaren,1487.040599,1488.400788,0.0,NaN,2
16,Jean Alesi,Ferrari,1481.463716,1497.912165,42.0,5.0,17
17,Domenico Schiattarella,Simtek,1479.962457,1486.264211,0.0,NaN,5
18,Pedro Diniz,Forti,1478.500772,1486.284729,0.0,NaN,17
19,Martin Brundle,Ligier,1475.150549,1478.877195,7.0,13.0,11
20,Massimiliano Papis,Footwork,1474.583203,1481.299862,0.0,NaN,7
21,Andrea Montermini,Pacific,1471.238221,1477.601269,0.0,NaN,17
22,Damon Hill,Williams,1466.199992,1494.852587,69.0,2.0,17
23,Olivier Panis,Ligier,1465.692989,1486.594883,16.0,8.0,17
24,David Coulthard,Williams,1463.971082,1486.436392,49.0,3.0,17
25,Karl Wendlinger,Sauber,1457.187639,1472.269148,0.0,NaN,6
26,Rubens Barrichello,Jordan,1456.526828,1485.756109,11.0,11.0,17
27,Giovanni Lavaggi,Pacific,1456.027376,1474.606793,0.0,NaN,4
28,Mark Blundell,McLaren,1453.687268,1470.222872,13.0,10.0,15
29,Roberto Moreno,Forti,1449.620532,1482.353495,0.0,NaN,17
30,Luca Badoer,Minardi,1443.075801,1466.510908,0.0,NaN,17
31,Aguri Suzuki,Ligier,1426.386284,1467.946612,1.0,17.0,6
32,Johnny Herbert,Benetton,1414.702491,1441.583908,45.0,4.0,17
33,Jean-Christophe Boullion,Sauber,1406.568407,1451.678150,3.0,16.0,11
34,Taki Inoue,Footwork,1401.758631,1436.412513,0.0,NaN,17
35,Ukyo Katayama,Tyrrell,1366.990359,1428.862324,0.0,NaN,16

## 1996

In [18]:
elo_standings(1996)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,Michael Schumacher,Ferrari,1545.767591,1520.153764,59.0,3.0,16
2,Mika Häkkinen,McLaren,1516.785915,1507.031225,31.0,5.0,16
3,Damon Hill,Williams,1514.791121,1518.773393,97.0,1.0,16
4,Jean Alesi,Benetton,1511.490841,1504.838113,47.0,4.0,16
5,Jacques Villeneuve,Williams,1511.317154,1483.086292,78.0,2.0,16
6,Luca Badoer,Forti,1494.290554,1497.657627,0.0,NaN,6
7,Giovanni Lavaggi,Minardi,1491.293818,1491.578459,0.0,NaN,3
8,Heinz-Harald Frentzen,Sauber,1488.529636,1500.213858,7.0,12.0,16
9,Mika Salo,Tyrrell,1487.290301,1502.252451,5.0,13.0,16
10,Rubens Barrichello,Jordan,1484.870700,1506.666749,14.0,8.0,16
11,Andrea Montermini,Forti,1480.706048,1481.122450,0.0,NaN,5
12,Gerhard Berger,Benetton,1476.205213,1482.954048,21.0,6.0,16
13,Olivier Panis,Ligier,1474.262267,1497.225959,13.0,9.0,16
14,Tarso Marques,Minardi,1471.466922,1473.746860,0.0,NaN,2
15,Giancarlo Fisichella,Minardi,1471.303458,1486.584782,0.0,NaN,8
16,David Coulthard,McLaren,1453.086036,1477.443605,18.0,7.0,16
17,Pedro Lamy,Minardi,1443.160588,1477.748417,0.0,NaN,16
18,Jos Verstappen,Footwork,1436.148618,1480.576366,1.0,16.0,16
19,Pedro Diniz,Ligier,1431.364694,1467.491142,2.0,15.0,16
20,Martin Brundle,Jordan,1424.986515,1433.997140,8.0,11.0,16
21,Eddie Irvine,Ferrari,1424.175652,1459.784045,11.0,10.0,16
22,Johnny Herbert,Sauber,1420.215595,1451.156270,4.0,14.0,16
23,Ukyo Katayama,Tyrrell,1405.468174,1440.599950,0.0,NaN,16
24,Ricardo Rosset,Footwork,1399.141144,1441.419282,0.0,NaN,16

## 1997

In [19]:
elo_standings(1997)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,Michael Schumacher,Ferrari,1562.424025,1544.293285,78.0,NaN,17
2,Olivier Panis,Prost,1529.982564,1525.961409,16.0,9.0,10
3,Johnny Herbert,Sauber,1513.940925,1509.720713,15.0,10.0,17
4,Mika Salo,Tyrrell,1509.244165,1512.077698,2.0,17.0,17
5,Jarno Trulli,Minardi,1507.223313,1507.300814,3.0,15.0,14
6,Gerhard Berger,Benetton,1503.916230,1499.452255,27.0,5.0,14
7,Rubens Barrichello,Stewart,1499.933640,1515.800106,6.0,13.0,17
8,Jacques Villeneuve,Williams,1499.775876,1490.943538,81.0,1.0,17
9,Damon Hill,Arrows,1496.194066,1500.248699,7.0,12.0,17
10,Jean Alesi,Benetton,1493.703742,1494.455664,36.0,4.0,17
11,Mika Häkkinen,McLaren,1489.333925,1488.439439,27.0,6.0,17
12,Alexander Wurz,Benetton,1483.849395,1488.676032,4.0,14.0,3
13,Heinz-Harald Frentzen,Williams,1480.196449,1472.359629,42.0,2.0,17
14,David Coulthard,McLaren,1474.641136,1480.703673,36.0,3.0,17
15,Tarso Marques,Minardi,1469.579758,1479.973683,0.0,NaN,10
16,Norberto Fontana,Sauber,1468.391989,1475.062318,0.0,NaN,4
17,Giancarlo Fisichella,Jordan,1464.056751,1472.368811,20.0,8.0,17
18,Nicola Larini,Sauber,1460.185409,1479.049166,1.0,19.0,5
19,Gianni Morbidelli,Sauber,1458.285347,1471.068805,0.0,NaN,8
20,Ralf Schumacher,Jordan,1442.290364,1478.126865,13.0,11.0,17
21,Pedro Diniz,Arrows,1422.707954,1458.636538,2.0,16.0,17
22,Jos Verstappen,Tyrrell,1410.515923,1455.304584,0.0,NaN,17
23,Shinji Nakano,Prost,1410.252371,1434.614882,2.0,18.0,17
24,Ukyo Katayama,Minardi,1405.809318,1450.868726,0.0,NaN,17
25,Jan Magnussen,Stewart,1400.495591,1435.914794,0.0,NaN,17
26,Eddie Irvine,Ferrari,1399.808629,1427.843165,24.0,7.0,17

## 1998

In [20]:
elo_standings(1998)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,Michael Schumacher,Ferrari,1578.037058,1548.917285,86.0,2.0,16
2,Mika Häkkinen,McLaren,1566.544275,1544.148410,100.0,1.0,16
3,Jean Alesi,Sauber,1497.057281,1491.800596,9.0,11.0,16
4,Rubens Barrichello,Stewart,1491.886901,1498.509222,4.0,12.0,16
5,Shinji Nakano,Minardi,1487.557337,1493.412244,0.0,NaN,16
6,Alexander Wurz,Benetton,1484.298596,1503.260838,17.0,8.0,16
7,Damon Hill,Jordan,1482.436666,1484.826211,20.0,6.0,16
8,Ralf Schumacher,Jordan,1481.472937,1479.469870,14.0,10.0,16
9,Jacques Villeneuve,Williams,1477.917156,1492.712800,21.0,5.0,16
10,Giancarlo Fisichella,Benetton,1477.232888,1475.516410,16.0,9.0,16
11,David Coulthard,McLaren,1476.221295,1480.745088,56.0,3.0,16
12,Jos Verstappen,Stewart,1474.277098,1484.994115,0.0,NaN,9
13,Heinz-Harald Frentzen,Williams,1470.782993,1478.861711,17.0,7.0,16
14,Jarno Trulli,Prost,1469.171322,1485.267010,1.0,16.0,16
15,Jan Magnussen,Stewart,1465.710855,1476.399219,1.0,17.0,7
16,Eddie Irvine,Ferrari,1465.108618,1473.626386,47.0,4.0,16
17,Mika Salo,Arrows,1463.005432,1488.692781,3.0,13.0,16
18,Toranosuke Takagi,Tyrrell,1454.688514,1482.028160,0.0,NaN,16
19,Ricardo Rosset,Tyrrell,1441.993613,1470.590613,0.0,NaN,11
20,Pedro Diniz,Arrows,1440.890808,1474.052995,3.0,14.0,16
21,Olivier Panis,Prost,1439.206309,1471.538717,0.0,NaN,16
22,Johnny Herbert,Sauber,1419.447930,1469.009602,1.0,15.0,16
23,Esteban Tuero,Minardi,1409.488514,1447.317611,0.0,NaN,16

## 1999

In [21]:
elo_standings(1999)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,Heinz-Harald Frentzen,Jordan,1546.868722,1519.160760,54.0,3.0,16
2,Eddie Irvine,Ferrari,1534.079719,1512.502742,74.0,2.0,16
3,Mika Häkkinen,McLaren,1524.274863,1513.293050,76.0,1.0,16
4,Michael Schumacher,Ferrari,1522.519789,1511.001192,44.0,5.0,10
5,David Coulthard,McLaren,1514.242493,1505.722328,48.0,4.0,16
6,Rubens Barrichello,Stewart,1503.864853,1507.025001,21.0,7.0,16
7,Johnny Herbert,Stewart,1499.412482,1489.791349,15.0,8.0,16
8,Ralf Schumacher,Williams,1493.696459,1502.412372,35.0,6.0,16
9,Jarno Trulli,Prost,1488.396408,1478.598859,7.0,11.0,16
10,Stéphane Sarrazin,Minardi,1486.046114,1486.046114,0.0,NaN,1
11,Giancarlo Fisichella,Benetton,1480.905237,1506.144407,13.0,9.0,16
12,Mika Salo,Ferrari,1479.749550,1483.199671,10.0,10.0,9
13,Jean Alesi,Sauber,1478.548494,1485.123366,2.0,15.0,16
14,Ricardo Zonta,BAR,1471.478633,1484.028179,0.0,NaN,12
15,Jacques Villeneuve,BAR,1464.849398,1481.047478,0.0,NaN,16
16,Pedro de la Rosa,Arrows,1463.120953,1483.784993,1.0,18.0,16
17,Olivier Panis,Prost,1462.691032,1485.575487,2.0,16.0,16
18,Toranosuke Takagi,Arrows,1446.125809,1470.341383,0.0,NaN,16
19,Alessandro Zanardi,Williams,1443.995339,1461.204985,0.0,NaN,16
20,Luca Badoer,Minardi,1439.396357,1475.128480,0.0,NaN,15
21,Marc Gené,Minardi,1429.112759,1457.924451,1.0,17.0,16
22,Damon Hill,Jordan,1426.993597,1452.384910,7.0,12.0,16
23,Alexander Wurz,Benetton,1424.323331,1446.924463,3.0,13.0,16
24,Pedro Diniz,Sauber,1393.567808,1459.409908,3.0,14.0,16

## 2000

In [22]:
elo_standings(2000)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,Mika Häkkinen,McLaren,1575.132475,1539.246917,89.0,2.0,17
2,Michael Schumacher,Ferrari,1554.839096,1528.226333,108.0,1.0,17
3,Jacques Villeneuve,BAR,1535.056948,1522.326344,17.0,7.0,17
4,Mika Salo,Sauber,1510.910640,1513.190701,6.0,11.0,17
5,Heinz-Harald Frentzen,Jordan,1507.013836,1505.081362,11.0,9.0,17
6,David Coulthard,McLaren,1503.814432,1499.208443,73.0,3.0,17
7,Rubens Barrichello,Ferrari,1500.041948,1502.829186,62.0,4.0,17
8,Ralf Schumacher,Williams,1497.859473,1504.968141,24.0,5.0,17
9,Giancarlo Fisichella,Benetton,1491.798166,1509.909730,18.0,6.0,17
10,Luciano Burti,Jaguar,1488.947193,1488.947193,0.0,NaN,1
11,Jenson Button,Williams,1477.819770,1485.547206,12.0,8.0,17
12,Jos Verstappen,Arrows,1473.696404,1483.142583,5.0,12.0,17
13,Johnny Herbert,Jaguar,1466.931569,1476.626870,0.0,NaN,17
14,Marc Gené,Minardi,1466.175392,1480.046984,0.0,NaN,17
15,Eddie Irvine,Jaguar,1461.472851,1476.112975,4.0,13.0,16
16,Jean Alesi,Prost,1458.734749,1476.403168,0.0,NaN,17
17,Nick Heidfeld,Prost,1454.182266,1486.429692,0.0,NaN,16
18,Alexander Wurz,Benetton,1436.005530,1456.427788,2.0,15.0,17
19,Jarno Trulli,Jordan,1429.562596,1470.950460,6.0,10.0,17
20,Pedro de la Rosa,Arrows,1426.094372,1463.888345,2.0,16.0,17
21,Gastón Mazzacane,Minardi,1413.400743,1452.567819,0.0,NaN,17
22,Pedro Diniz,Sauber,1407.504906,1450.688296,0.0,NaN,17
23,Ricardo Zonta,BAR,1398.850370,1435.532614,3.0,14.0,17

## 2001

In [23]:
elo_standings(2001)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,Michael Schumacher,Ferrari,1606.602525,1566.595537,123.0,1.0,17
2,David Coulthard,McLaren,1558.826597,1539.512326,65.0,2.0,17
3,Ralf Schumacher,Williams,1509.474094,1504.954778,49.0,4.0,17
4,Mika Häkkinen,McLaren,1505.809940,1498.535015,37.0,5.0,17
5,Jarno Trulli,Jordan,1498.762106,1500.739598,12.0,9.0,17
6,Giancarlo Fisichella,Benetton,1496.026407,1495.010555,8.0,11.0,17
7,Gastón Mazzacane,Prost,1490.820614,1493.115461,0.0,NaN,4
8,Rubens Barrichello,Ferrari,1489.145209,1483.793687,56.0,3.0,17
9,Ricardo Zonta,Jordan,1489.135779,1493.746890,0.0,NaN,2
10,Jacques Villeneuve,BAR,1487.800365,1475.363153,12.0,7.0,17
11,Fernando Alonso,Minardi,1487.172284,1490.732494,0.0,NaN,17
12,Heinz-Harald Frentzen,Jordan,1483.348998,1488.400392,6.0,13.0,15
13,Tomáš Enge,Prost,1482.633655,1486.793723,0.0,NaN,3
14,Kimi Räikkönen,Sauber,1477.761611,1487.799576,9.0,10.0,17
15,Olivier Panis,BAR,1473.167832,1500.533728,5.0,14.0,17
16,Juan Pablo Montoya,Williams,1470.741135,1463.403559,31.0,6.0,17
17,Alex Yoong,Minardi,1470.412965,1479.100850,0.0,NaN,3
18,Jos Verstappen,Arrows,1466.365298,1489.975501,1.0,18.0,17
19,Jean Alesi,Prost,1462.689403,1489.972195,5.0,15.0,17
20,Nick Heidfeld,Sauber,1461.911633,1477.925962,12.0,8.0,17
21,Tarso Marques,Minardi,1457.810978,1474.069276,0.0,NaN,13
22,Pedro de la Rosa,Jaguar,1455.765561,1476.333907,3.0,16.0,13
23,Eddie Irvine,Jaguar,1454.652414,1470.626899,6.0,12.0,17
24,Luciano Burti,Prost,1429.080063,1476.876713,0.0,NaN,14
25,Jenson Button,Benetton,1420.575950,1456.740626,2.0,17.0,17
26,Enrique Bernoldi,Arrows,1415.637161,1441.461862,0.0,NaN,17

## 2002

In [24]:
elo_standings(2002)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,Michael Schumacher,Ferrari,1588.492419,1556.834576,144.0,1.0,17
2,Juan Pablo Montoya,Williams,1537.889168,1517.757480,50.0,3.0,17
3,Rubens Barrichello,Ferrari,1518.960216,1493.026466,77.0,2.0,17
4,Ralf Schumacher,Williams,1516.683966,1510.023176,42.0,4.0,17
5,David Coulthard,McLaren,1513.785779,1507.306714,41.0,5.0,17
6,Kimi Räikkönen,McLaren,1498.040145,1500.981086,24.0,6.0,17
7,Eddie Irvine,Jaguar,1494.157656,1498.274191,8.0,9.0,17
8,Mark Webber,Minardi,1492.499087,1492.759413,2.0,16.0,17
9,Jacques Villeneuve,BAR,1490.622683,1493.735523,4.0,12.0,17
10,Nick Heidfeld,Sauber,1489.697967,1487.631505,7.0,10.0,17
11,Giancarlo Fisichella,Jordan,1488.220375,1486.924280,7.0,11.0,17
12,Jarno Trulli,Renault,1482.745242,1480.125913,9.0,8.0,17
13,Heinz-Harald Frentzen,Arrows,1480.739301,1493.457156,2.0,18.0,12
14,Mika Salo,Toyota,1480.628477,1491.739101,2.0,17.0,17
15,Anthony Davidson,Minardi,1472.309242,1478.360379,0.0,NaN,2
16,Jenson Button,Renault,1471.911403,1489.593111,14.0,7.0,17
17,Enrique Bernoldi,Arrows,1467.767554,1478.457544,0.0,22.0,11
18,Olivier Panis,BAR,1464.066661,1477.735818,3.0,14.0,17
19,Pedro de la Rosa,Jaguar,1438.306157,1462.361057,0.0,21.0,17
20,Felipe Massa,Sauber,1433.643442,1468.395511,4.0,13.0,16
21,Allan McNish,Toyota,1426.331775,1451.376367,0.0,19.0,17
22,Takuma Sato,Jordan,1421.469587,1456.789068,2.0,15.0,17
23,Alex Yoong,Minardi,1415.218221,1456.450259,0.0,20.0,12

## 2003

In [25]:
elo_standings(2003)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,Giancarlo Fisichella,Jordan,1531.594699,1517.259742,12.0,12,16
2,Kimi Räikkönen,McLaren,1525.887951,1511.339774,91.0,2,16
3,Michael Schumacher,Ferrari,1523.624563,1521.186602,93.0,1,16
4,Fernando Alonso,Renault,1522.071669,1520.942880,55.0,6,16
5,Juan Pablo Montoya,Williams,1513.473370,1491.563681,82.0,3,16
6,Mark Webber,Jaguar,1508.610506,1507.152638,17.0,10,16
7,Jos Verstappen,Minardi,1508.222133,1486.368006,0.0,22,16
8,Jenson Button,BAR,1507.198005,1489.501208,17.0,9,16
9,Nick Heidfeld,Sauber,1504.946622,1507.829302,6.0,14,16
10,Takuma Sato,BAR,1492.736502,1492.736502,3.0,18,1
11,Marc Gené,Williams,1491.045562,1491.045562,4.0,17,1
12,Zsolt Baumgartner,Jordan,1487.931755,1492.553151,0.0,24,2
13,Jacques Villeneuve,BAR,1485.188159,1497.485255,6.0,16,15
14,Justin Wilson,Minardi,1479.839686,1492.674700,1.0,20,16
15,Olivier Panis,Toyota,1477.447165,1497.319388,6.0,15,16
16,Ralf Schumacher,Williams,1473.644011,1503.074689,58.0,5,15
17,Nicolas Kiesa,Minardi,1468.666793,1482.747479,0.0,23,5
18,David Coulthard,McLaren,1465.973822,1485.774681,51.0,7,16
19,Jarno Trulli,Renault,1459.457759,1468.565881,33.0,8,16
20,Cristiano da Matta,Toyota,1457.932025,1464.173318,10.0,13,16
21,Heinz-Harald Frentzen,Sauber,1455.360615,1471.670534,13.0,11,16
22,Rubens Barrichello,Ferrari,1448.062978,1462.655658,65.0,4,16
23,Antônio Pizzonia,Jaguar,1441.866628,1464.348528,0.0,21,11
24,Ralph Firman,Jordan,1429.951448,1461.911590,1.0,19,14

## 2004

In [26]:
elo_standings(2004)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,Michael Schumacher,Ferrari,1557.148586,1552.835922,148.0,1,18
2,Juan Pablo Montoya,Williams,1545.960651,1521.676229,58.0,5,18
3,Jenson Button,BAR,1545.867103,1528.277883,85.0,3,18
4,Nick Heidfeld,Jordan,1544.117222,1520.993995,3.0,18,18
5,Kimi Räikkönen,McLaren,1536.060498,1511.248810,45.0,7,18
6,Giancarlo Fisichella,Sauber,1521.213141,1509.520227,22.0,11,18
7,Jarno Trulli,Renault,1510.108086,1507.184889,46.0,6,17
8,Mark Webber,Jaguar,1509.230675,1508.428173,7.0,13,18
9,Fernando Alonso,Renault,1506.222811,1489.245101,59.0,4,18
10,Ricardo Zonta,Toyota,1488.851275,1495.709281,0.0,22,5
11,Timo Glock,Jordan,1482.537012,1490.902166,2.0,19,4
12,Marc Gené,Williams,1481.914694,1486.707346,0.0,23,2
13,Antônio Pizzonia,Williams,1481.550950,1487.666451,6.0,15,4
14,Gianmaria Bruni,Minardi,1480.669956,1495.394799,0.0,25,18
15,Jacques Villeneuve,Renault,1476.171304,1483.720569,0.0,21,3
16,Cristiano da Matta,Toyota,1474.905639,1487.035694,3.0,17,12
17,Ralf Schumacher,Williams,1474.513279,1488.507655,24.0,9,12
18,Rubens Barrichello,Ferrari,1470.442582,1470.217619,114.0,2,18
19,Takuma Sato,BAR,1455.281059,1473.152973,34.0,8,18
20,Zsolt Baumgartner,Minardi,1450.526766,1470.643222,1.0,20,18
21,Olivier Panis,Toyota,1449.859999,1479.362114,6.0,14,17
22,Felipe Massa,Sauber,1441.745030,1465.427917,12.0,12,18
23,David Coulthard,McLaren,1441.089093,1473.942105,24.0,10,18
24,Giorgio Pantano,Jordan,1417.782750,1465.204946,0.0,24,14
25,Christian Klien,Jaguar,1403.693462,1445.507400,3.0,16,18

## 2005

In [27]:
elo_standings(2005)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,Fernando Alonso,Renault,1567.076864,1544.608373,133.0,1.0,19
2,Jenson Button,BAR,1562.749323,1530.740636,37.0,9.0,17
3,Kimi Räikkönen,McLaren,1531.636254,1510.601271,112.0,2.0,19
4,Felipe Massa,Sauber,1525.071465,1513.914159,11.0,13.0,19
5,Christijan Albers,Minardi,1513.096993,1506.106333,4.0,19.0,19
6,Michael Schumacher,Ferrari,1503.845616,1501.741052,62.0,3.0,19
7,Tiago Monteiro,Jordan,1503.095516,1492.006900,7.0,16.0,19
8,Mark Webber,Williams,1500.548139,1487.896629,36.0,10.0,19
9,Ricardo Zonta,Toyota,1497.348388,1497.348388,0.0,NaN,1
10,Anthony Davidson,BAR,1497.068744,1497.068744,0.0,NaN,1
11,Alexander Wurz,McLaren,1497.029377,1497.029377,6.0,17.0,1
12,Pedro de la Rosa,McLaren,1496.797152,1496.797152,4.0,20.0,1
13,Jarno Trulli,Toyota,1495.252421,1531.301112,43.0,7.0,19
14,Nick Heidfeld,Williams,1488.601632,1486.446596,28.0,11.0,14
15,Robert Doornbos,Minardi,1487.577272,1489.416523,0.0,25.0,8
16,David Coulthard,Red Bull,1482.259306,1506.704888,24.0,12.0,19
17,Ralf Schumacher,Toyota,1480.364073,1465.844670,45.0,6.0,18
18,Narain Karthikeyan,Jordan,1474.185818,1503.343753,5.0,18.0,19
19,Christian Klien,Red Bull,1471.156974,1475.426743,9.0,15.0,15
20,Juan Pablo Montoya,McLaren,1467.942746,1489.745257,60.0,4.0,17
21,Vitantonio Liuzzi,Red Bull,1461.347263,1478.935887,1.0,24.0,4
22,Rubens Barrichello,Ferrari,1458.161093,1481.854364,38.0,8.0,19
23,Patrick Friesacher,Minardi,1447.621567,1471.279808,3.0,21.0,11
24,Antônio Pizzonia,Williams,1442.438313,1468.877901,2.0,22.0,5
25,Jacques Villeneuve,Sauber,1438.712811,1463.372127,9.0,14.0,19
26,Giancarlo Fisichella,Renault,1433.627608,1453.949961,58.0,5.0,19
27,Takuma Sato,BAR,1399.256379,1447.800257,1.0,23.0,16

## 2006

In [28]:
elo_standings(2006)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,Fernando Alonso,Renault,1576.352355,1543.131635,134.0,1,18
2,Michael Schumacher,Ferrari,1550.657331,1537.468975,121.0,2,18
3,Jenson Button,Honda,1528.767471,1512.505565,56.0,6,18
4,Takuma Sato,Super Aguri,1515.749726,1510.142246,0.0,23,18
5,Kimi Räikkönen,McLaren,1511.911543,1498.058464,65.0,5,18
6,Nick Heidfeld,BMW Sauber,1494.553451,1497.769372,23.0,9,18
7,David Coulthard,Red Bull,1493.103646,1491.269127,14.0,13,18
8,Robert Doornbos,Red Bull,1490.703735,1492.013075,0.0,24,3
9,Robert Kubica,BMW Sauber,1485.395556,1490.648099,6.0,16,6
10,Yuji Ide,Super Aguri,1483.171360,1490.003411,0.0,25,4
11,Jarno Trulli,Toyota,1478.056741,1472.380586,15.0,12,18
12,Ralf Schumacher,Toyota,1477.091633,1496.449035,20.0,10,18
13,Rubens Barrichello,Honda,1476.844259,1487.270826,30.0,7,18
14,Pedro de la Rosa,McLaren,1475.450397,1490.005848,19.0,11,8
15,Christijan Albers,MF1,1470.505904,1481.286835,0.0,22,18
16,Sakon Yamamoto,Super Aguri,1469.763130,1483.679035,0.0,26,7
17,Franck Montagny,Super Aguri,1468.186389,1483.085542,0.0,27,7
18,Giancarlo Fisichella,Renault,1457.791181,1478.132180,72.0,4,18
19,Jacques Villeneuve,BMW Sauber,1456.622328,1485.845428,7.0,15,12
20,Felipe Massa,Ferrari,1448.657267,1455.187364,80.0,3,18
21,Scott Speed,Toro Rosso,1445.947362,1459.661708,0.0,20,18
22,Vitantonio Liuzzi,Toro Rosso,1445.844988,1477.539415,1.0,19,18
23,Juan Pablo Montoya,McLaren,1445.584353,1490.741786,26.0,8,10
24,Mark Webber,Williams,1444.902736,1490.549114,7.0,14,18
25,Tiago Monteiro,MF1,1437.610889,1475.138173,0.0,21,18
26,Christian Klien,Red Bull,1434.533686,1469.778676,2.0,18,15
27,Nico Rosberg,Williams,1406.044693,1442.004925,4.0,17,18

## 2007

In [29]:
elo_standings(2007)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,Nick Heidfeld,BMW Sauber,1558.153746,1534.946533,61.0,5.0,17
2,Kimi Räikkönen,Ferrari,1536.539910,1512.372197,110.0,1.0,17
3,Mark Webber,Red Bull,1532.606949,1527.670256,10.0,12.0,17
4,Nico Rosberg,Williams,1529.888841,1516.275381,20.0,9.0,17
5,Heikki Kovalainen,Renault,1520.725288,1506.246895,30.0,7.0,17
6,Fernando Alonso,McLaren,1514.053691,1511.151847,109.0,3.0,17
7,Jarno Trulli,Toyota,1509.323797,1510.793811,8.0,13.0,17
8,Adrian Sutil,Spyker,1502.879282,1496.087289,1.0,19.0,17
9,Markus Winkelhock,Spyker,1496.920026,1496.920026,0.0,NaN,1
10,Lewis Hamilton,McLaren,1493.234741,1505.591351,109.0,2.0,17
11,Kazuki Nakajima,Williams,1489.631648,1489.631648,0.0,22.0,1
12,Felipe Massa,Ferrari,1484.422744,1496.698369,94.0,4.0,17
13,Robert Kubica,BMW Sauber,1478.403913,1484.122518,39.0,6.0,16
14,Takuma Sato,Super Aguri,1470.445258,1494.009153,4.0,17.0,17
15,Sebastian Vettel,Toro Rosso,1469.280957,1477.779328,6.0,14.0,8
16,Jenson Button,Honda,1463.894400,1460.828564,6.0,15.0,17
17,Christijan Albers,Spyker,1463.711537,1473.396602,0.0,25.0,9
18,Giancarlo Fisichella,Renault,1462.615822,1496.003994,21.0,8.0,17
19,Rubens Barrichello,Honda,1458.411815,1491.970515,0.0,20.0,17
20,Vitantonio Liuzzi,Toro Rosso,1454.007013,1467.380230,3.0,18.0,17
21,Scott Speed,Toro Rosso,1448.770094,1479.493437,0.0,21.0,10
22,Anthony Davidson,Super Aguri,1448.266333,1461.001318,0.0,23.0,17
23,Ralf Schumacher,Toyota,1446.996751,1472.275999,5.0,16.0,17
24,Sakon Yamamoto,Spyker,1442.994830,1460.431554,0.0,24.0,7
25,David Coulthard,Red Bull,1434.678326,1454.635577,14.0,10.0,17
26,Alexander Wurz,Williams,1430.618083,1455.743013,13.0,11.0,16

## 2008

In [30]:
elo_standings(2008)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,Lewis Hamilton,McLaren,1568.760656,1536.645010,98.0,1,18
2,Felipe Massa,Ferrari,1560.987078,1528.790585,97.0,2,18
3,Sebastian Vettel,Toro Rosso,1544.265631,1497.620345,35.0,8,18
4,Fernando Alonso,Renault,1539.649431,1519.945631,61.0,5,18
5,Robert Kubica,BMW Sauber,1536.470662,1541.220526,75.0,4,18
6,Mark Webber,Red Bull,1532.330825,1523.482925,21.0,11,18
7,Anthony Davidson,Super Aguri,1501.689988,1494.784378,0.0,22,4
8,Jarno Trulli,Toyota,1499.283668,1516.390391,31.0,9,18
9,Nick Heidfeld,BMW Sauber,1495.698296,1486.268964,60.0,6,18
10,Heikki Kovalainen,McLaren,1491.660522,1494.380766,53.0,7,18
11,Nico Rosberg,Williams,1486.885121,1499.849937,17.0,13,18
12,Takuma Sato,Super Aguri,1486.776077,1494.631887,0.0,21,4
13,Kimi Räikkönen,Ferrari,1477.051224,1491.199629,75.0,3,18
14,Timo Glock,Toyota,1464.880058,1455.803179,25.0,10,18
15,Rubens Barrichello,Honda,1445.590504,1466.900620,11.0,14,18
16,Giancarlo Fisichella,Force India,1435.463206,1470.941443,0.0,19,18
17,Adrian Sutil,Force India,1435.400887,1454.886377,0.0,20,18
18,Jenson Button,Honda,1426.418718,1456.783268,3.0,18,18
19,Sébastien Bourdais,Toro Rosso,1406.930233,1442.332472,4.0,17,18
20,Kazuki Nakajima,Williams,1405.942456,1435.877196,9.0,15,18
21,David Coulthard,Red Bull,1370.949713,1425.561763,8.0,16,18
22,Nelson Piquet Jr.,Renault,1364.842588,1435.899979,19.0,12,18

## 2009

In [31]:
elo_standings(2009)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,Kimi Räikkönen,Ferrari,1557.464722,1518.392979,48.0,6,17
2,Fernando Alonso,Renault,1553.631398,1543.995927,26.0,9,17
3,Nico Rosberg,Williams,1550.622209,1535.892797,34.5,7,17
4,Jenson Button,Brawn,1545.772275,1545.260476,95.0,1,17
5,Sebastian Vettel,Red Bull,1544.534397,1509.052528,84.0,2,17
6,Rubens Barrichello,Brawn,1525.272881,1498.284275,77.0,3,17
7,Felipe Massa,Ferrari,1512.826181,1507.616142,22.0,11,10
8,Lewis Hamilton,McLaren,1512.747295,1499.821909,49.0,5,17
9,Kamui Kobayashi,Toyota,1501.440867,1501.185714,3.0,18,2
10,Sébastien Buemi,Toro Rosso,1495.639560,1485.763725,6.0,16,17
11,Timo Glock,Toyota,1495.113786,1499.824713,24.0,10,15
12,Mark Webber,Red Bull,1492.064896,1501.834935,69.5,4,17
13,Robert Kubica,BMW Sauber,1489.936631,1483.651484,17.0,14,17
14,Vitantonio Liuzzi,Force India,1487.379302,1489.165414,0.0,22,5
15,Luca Badoer,Ferrari,1479.098684,1484.620695,0.0,25,2
16,Nick Heidfeld,BMW Sauber,1475.909842,1479.302197,19.0,13,17
17,Sébastien Bourdais,Toro Rosso,1458.850827,1479.904914,2.0,19,9
18,Jarno Trulli,Toyota,1458.600608,1488.832449,32.5,8,17
19,Romain Grosjean,Renault,1446.503073,1463.182543,0.0,23,7
20,Giancarlo Fisichella,Force India,1445.758674,1486.523947,8.0,15,17
21,Jaime Alguersuari,Toro Rosso,1442.404169,1467.059242,0.0,24,8
22,Heikki Kovalainen,McLaren,1429.965870,1447.796909,22.0,12,17
23,Adrian Sutil,Force India,1424.080424,1461.850999,5.0,17,17
24,Nelson Piquet Jr.,Renault,1423.742475,1443.903421,0.0,21,10
25,Kazuki Nakajima,Williams,1401.158242,1435.623633,0.0,20,17

## 2010

In [32]:
elo_standings(2010)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,Robert Kubica,Renault,1573.761109,1547.381241,136.0,8,19
2,Fernando Alonso,Ferrari,1565.081133,1529.462722,252.0,2,19
3,Nico Rosberg,Mercedes,1550.893244,1539.397943,142.0,7,19
4,Sebastian Vettel,Red Bull,1545.912438,1518.589361,256.0,1,19
5,Lewis Hamilton,McLaren,1539.847700,1523.304827,240.0,4,19
6,Timo Glock,Virgin,1510.340305,1503.749540,0.0,25,19
7,Rubens Barrichello,Williams,1509.752929,1512.408346,47.0,10,19
8,Bruno Senna,HRT,1509.272005,1497.968945,0.0,23,18
9,Adrian Sutil,Force India,1505.552370,1508.736563,47.0,11,19
10,Kamui Kobayashi,Sauber,1490.390550,1479.567541,32.0,12,19
11,Christian Klien,HRT,1490.305191,1497.494813,0.0,27,3
12,Jarno Trulli,Lotus,1489.328058,1497.492094,0.0,21,19
13,Karun Chandhok,HRT,1488.958648,1481.346445,0.0,22,10
14,Jaime Alguersuari,Toro Rosso,1480.456431,1478.292732,5.0,19,19
15,Heikki Kovalainen,Lotus,1479.021321,1482.857032,0.0,20,19
16,Mark Webber,Red Bull,1478.169375,1497.316094,242.0,3,19
17,Nick Heidfeld,Sauber,1471.375987,1478.438876,6.0,18,5
18,Jenson Button,McLaren,1470.805592,1489.436413,214.0,5,19
19,Sakon Yamamoto,HRT,1461.867219,1475.601272,0.0,26,7
20,Pedro de la Rosa,Sauber,1459.652830,1482.667295,6.0,17,14
21,Sébastien Buemi,Toro Rosso,1442.378341,1470.637988,8.0,16,19
22,Lucas di Grassi,Virgin,1440.509090,1471.693516,0.0,24,19
23,Nico Hülkenberg,Williams,1439.765726,1460.731664,22.0,14,19
24,Michael Schumacher,Mercedes,1438.018819,1465.071813,72.0,9,19
25,Felipe Massa,Ferrari,1436.597742,1477.907483,144.0,6,19
26,Vitantonio Liuzzi,Force India,1398.165637,1455.569702,21.0,15,19
27,Vitaly Petrov,Renault,1384.286971,1433.304703,27.0,13,19

## 2011

In [33]:
elo_standings(2011)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,Sebastian Vettel,Red Bull,1592.214633,1561.167680,392.0,1,19
2,Fernando Alonso,Ferrari,1569.183887,1536.535547,257.0,4,19
3,Heikki Kovalainen,Lotus,1535.472226,1509.852508,0.0,22,19
4,Jenson Button,McLaren,1515.913430,1501.530863,270.0,2,19
5,Nico Rosberg,Mercedes,1514.958599,1506.621402,89.0,7,19
6,Adrian Sutil,Force India,1514.950045,1493.263957,42.0,9,19
7,Daniel Ricciardo,HRT,1507.109629,1501.144161,0.0,27,11
8,Lewis Hamilton,McLaren,1503.653671,1509.030758,227.0,5,19
9,Rubens Barrichello,Williams,1495.223519,1504.315390,4.0,17,19
10,Timo Glock,Virgin,1492.847735,1504.329520,0.0,25,19
11,Vitantonio Liuzzi,HRT,1492.783006,1513.495224,0.0,23,17
12,Karun Chandhok,Lotus,1489.947699,1489.947699,0.0,28,1
13,Pedro de la Rosa,Sauber,1489.664421,1489.664421,0.0,20,1
14,Kamui Kobayashi,Sauber,1487.311982,1501.366064,30.0,12,19
15,Sébastien Buemi,Toro Rosso,1485.743828,1505.459237,15.0,15,19
16,Vitaly Petrov,Renault,1480.769088,1482.357480,37.0,10,19
17,Bruno Senna,Renault,1477.220973,1492.956736,2.0,18,8
18,Nick Heidfeld,Renault,1477.105135,1490.090605,34.0,11,11
19,Pastor Maldonado,Williams,1474.447708,1480.029338,1.0,19,19
20,Paul di Resta,Force India,1473.781697,1494.824693,27.0,13,19
21,Sergio Pérez,Sauber,1471.966364,1475.496111,14.0,16,18
22,Narain Karthikeyan,HRT,1465.103529,1476.429721,0.0,26,8
23,Jérôme d'Ambrosio,Virgin,1464.168480,1474.292540,0.0,24,19
24,Jaime Alguersuari,Toro Rosso,1458.437185,1465.170927,26.0,14,19
25,Jarno Trulli,Lotus,1449.208428,1480.527932,0.0,21,18
26,Michael Schumacher,Mercedes,1446.142075,1471.366902,76.0,8,19
27,Mark Webber,Red Bull,1441.656642,1459.129790,258.0,3,19
28,Felipe Massa,Ferrari,1441.628683,1466.020725,118.0,6,19

## 2012

In [34]:
elo_standings(2012)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,Fernando Alonso,Ferrari,1577.744159,1560.447566,278.0,2,20
2,Kimi Räikkönen,Lotus F1,1563.453454,1527.823033,207.0,3,20
3,Sebastian Vettel,Red Bull,1555.831493,1527.152295,281.0,1,20
4,Lewis Hamilton,McLaren,1526.988639,1522.740559,190.0,4,20
5,Pedro de la Rosa,HRT,1513.610178,1510.432811,0.0,25,19
6,Nico Hülkenberg,Force India,1510.018897,1486.547704,63.0,11,20
7,Timo Glock,Marussia,1507.301381,1513.130972,0.0,20,20
8,Daniel Ricciardo,Toro Rosso,1506.138555,1504.148529,10.0,18,20
9,Michael Schumacher,Mercedes,1501.393325,1499.308087,49.0,13,20
10,Jérôme d'Ambrosio,Lotus F1,1490.162560,1490.162560,0.0,23,1
11,Vitaly Petrov,Caterham,1489.858643,1488.970244,0.0,19,20
12,Pastor Maldonado,Williams,1485.572561,1485.884058,45.0,15,20
13,Mark Webber,Red Bull,1482.077852,1497.600981,179.0,6,20
14,Heikki Kovalainen,Caterham,1480.550444,1493.058107,0.0,22,20
15,Charles Pic,Marussia,1464.234229,1471.821531,0.0,21,20
16,Jenson Button,McLaren,1461.667214,1475.033440,188.0,5,20
17,Kamui Kobayashi,Sauber,1461.221117,1481.029802,60.0,12,20
18,Nico Rosberg,Mercedes,1455.787240,1488.937542,93.0,9,20
19,Paul di Resta,Force India,1453.111439,1495.266749,46.0,14,20
20,Sergio Pérez,Sauber,1447.619302,1481.996516,66.0,10,20
21,Bruno Senna,Williams,1443.285376,1475.435102,31.0,16,20
22,Jean-Éric Vergne,Toro Rosso,1439.020880,1466.255803,16.0,17,20
23,Felipe Massa,Ferrari,1432.371142,1442.691782,122.0,7,20
24,Narain Karthikeyan,HRT,1406.491656,1450.850704,0.0,24,19
25,Romain Grosjean,Lotus F1,1405.579903,1452.620435,96.0,8,19

## 2013

In [35]:
elo_standings(2013)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,Sebastian Vettel,Red Bull,1610.089738,1570.986477,397.0,1,19
2,Fernando Alonso,Ferrari,1568.429948,1539.195155,242.0,2,19
3,Nico Hülkenberg,Sauber,1545.602930,1529.117909,51.0,10,19
4,Jules Bianchi,Marussia,1531.429705,1530.913479,0.0,19,19
5,Nico Rosberg,Mercedes,1523.273448,1505.311301,171.0,6,19
6,Lewis Hamilton,Mercedes,1521.203200,1523.484475,189.0,4,19
7,Jenson Button,McLaren,1520.808806,1520.908897,73.0,9,19
8,Charles Pic,Caterham,1509.158689,1517.025014,0.0,20,19
9,Daniel Ricciardo,Toro Rosso,1505.283529,1497.678205,20.0,14,19
10,Kimi Räikkönen,Lotus F1,1503.969968,1529.309958,183.0,5,17
11,Romain Grosjean,Lotus F1,1498.786736,1473.128418,132.0,7,19
12,Sergio Pérez,McLaren,1491.232550,1483.180963,49.0,11,19
13,Heikki Kovalainen,Lotus F1,1485.057712,1487.294320,0.0,22,2
14,Paul di Resta,Force India,1475.659478,1486.785173,48.0,12,19
15,Pastor Maldonado,Williams,1472.346015,1476.103195,1.0,18,19
16,Valtteri Bottas,Williams,1467.129736,1491.556705,4.0,17,19
17,Jean-Éric Vergne,Toro Rosso,1458.824310,1481.111999,13.0,15,19
18,Mark Webber,Red Bull,1441.833647,1462.844305,199.0,3,19
19,Felipe Massa,Ferrari,1437.484530,1457.397660,112.0,8,19
20,Giedo van der Garde,Caterham,1432.459943,1451.948478,0.0,21,19
21,Adrian Sutil,Force India,1430.401681,1472.632545,29.0,13,19
22,Max Chilton,Marussia,1417.871139,1442.672800,0.0,23,19
23,Esteban Gutiérrez,Sauber,1392.554061,1431.587825,6.0,16,19

## 2014

In [36]:
elo_standings(2014)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,Fernando Alonso,Ferrari,1586.119396,1556.529260,161.0,6.0,19
2,Jenson Button,McLaren,1552.318680,1527.464931,126.0,8.0,19
3,Daniel Ricciardo,Red Bull,1544.778964,1526.990322,238.0,3.0,19
4,Lewis Hamilton,Mercedes,1527.827612,1517.960039,384.0,1.0,19
5,Valtteri Bottas,Williams,1524.279993,1522.895904,186.0,4.0,19
6,Kamui Kobayashi,Caterham,1516.675027,1510.781863,0.0,22.0,16
7,Jules Bianchi,Marussia,1511.118084,1501.152005,2.0,17.0,15
8,André Lotterer,Caterham,1502.606349,1502.606349,0.0,NaN,1
9,Nico Hülkenberg,Force India,1502.411783,1509.782380,96.0,9.0,19
10,Nico Rosberg,Mercedes,1500.594132,1500.911694,317.0,2.0,19
11,Daniil Kvyat,Toro Rosso,1499.238376,1499.797966,8.0,15.0,19
12,Will Stevens,Caterham,1496.871186,1496.871186,0.0,23.0,1
13,Jean-Éric Vergne,Toro Rosso,1492.085762,1502.585019,22.0,13.0,19
14,Romain Grosjean,Lotus F1,1487.106675,1504.964000,8.0,14.0,19
15,Sebastian Vettel,Red Bull,1471.998208,1479.283172,167.0,5.0,19
16,Pastor Maldonado,Lotus F1,1467.499746,1469.608132,2.0,16.0,19
17,Esteban Gutiérrez,Sauber,1464.440919,1466.513334,0.0,20.0,19
18,Felipe Massa,Williams,1463.274062,1465.742461,134.0,7.0,19
19,Kevin Magnussen,McLaren,1460.635626,1481.908202,55.0,11.0,19
20,Sergio Pérez,Force India,1453.229126,1470.988732,59.0,10.0,19
21,Marcus Ericsson,Caterham,1453.076590,1468.763929,0.0,19.0,16
22,Adrian Sutil,Sauber,1447.810029,1477.580791,0.0,18.0,19
23,Max Chilton,Marussia,1418.660288,1458.470924,0.0,21.0,16
24,Kimi Räikkönen,Ferrari,1415.718753,1443.631346,55.0,12.0,19

## 2015

In [37]:
elo_standings(2015)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,Sebastian Vettel,Ferrari,1553.614965,1540.023533,278.0,3.0,19
2,Lewis Hamilton,Mercedes,1547.176306,1545.886527,381.0,1.0,19
3,Alexander Rossi,Manor Marussia,1512.541550,1509.222842,0.0,20.0,5
4,Valtteri Bottas,Williams,1511.605952,1509.341090,136.0,5.0,19
5,Daniel Ricciardo,Red Bull,1505.624095,1506.884065,92.0,8.0,19
6,Romain Grosjean,Lotus F1,1505.133708,1508.412460,51.0,11.0,19
7,Nico Rosberg,Mercedes,1500.763980,1483.241411,322.0,2.0,19
8,Felipe Nasr,Sauber,1500.462888,1510.327203,27.0,13.0,19
9,Felipe Massa,Williams,1499.421541,1502.107851,121.0,6.0,19
10,Kevin Magnussen,McLaren,1497.000000,1497.000000,0.0,NaN,1
11,Will Stevens,Manor Marussia,1496.218525,1504.152901,0.0,21.0,18
12,Carlos Sainz,Toro Rosso,1494.583734,1503.349158,18.0,15.0,19
13,Sergio Pérez,Force India,1494.573372,1490.284237,78.0,9.0,19
14,Roberto Merhi,Manor Marussia,1483.301181,1484.280874,0.0,19.0,13
15,Jenson Button,McLaren,1482.513806,1485.219396,16.0,16.0,19
16,Daniil Kvyat,Red Bull,1481.800026,1492.032604,95.0,7.0,19
17,Max Verstappen,Toro Rosso,1475.316353,1477.495088,49.0,12.0,19
18,Fernando Alonso,McLaren,1474.991394,1495.193968,11.0,17.0,18
19,Nico Hülkenberg,Force India,1466.407711,1488.388068,58.0,10.0,19
20,Marcus Ericsson,Sauber,1449.058443,1456.005174,9.0,18.0,19
21,Kimi Räikkönen,Ferrari,1443.145386,1464.452522,150.0,4.0,19
22,Pastor Maldonado,Lotus F1,1396.043794,1439.017976,27.0,14.0,19

## 2016

In [38]:
elo_standings(2016)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,Daniel Ricciardo,Red Bull,1542.420869,1533.799623,256.0,3,21
2,Valtteri Bottas,Williams,1533.541095,1514.169582,85.0,8,21
3,Fernando Alonso,McLaren,1523.267409,1510.597723,54.0,10,20
4,Carlos Sainz,Toro Rosso,1521.127135,1515.904034,46.0,12,21
5,Lewis Hamilton,Mercedes,1516.976691,1493.546584,380.0,2,21
6,Sebastian Vettel,Ferrari,1511.301875,1510.145331,212.0,4,21
7,Sergio Pérez,Force India,1505.352965,1503.607593,101.0,7,21
8,Stoffel Vandoorne,McLaren,1503.300503,1503.300503,1.0,20,1
9,Max Verstappen,Red Bull,1502.622939,1496.271815,204.0,5,21
10,Marcus Ericsson,Sauber,1499.165470,1508.581262,0.0,22,21
11,Romain Grosjean,Haas F1 Team,1496.213396,1503.679803,29.0,13,21
12,Pascal Wehrlein,Manor Marussia,1493.971987,1512.520431,1.0,19,21
13,Nico Rosberg,Mercedes,1492.825902,1503.784852,385.0,1,21
14,Esteban Ocon,Manor Marussia,1492.181943,1491.994891,0.0,23,9
15,Kevin Magnussen,Renault,1485.516377,1499.598657,7.0,16,21
16,Esteban Gutiérrez,Haas F1 Team,1475.245744,1476.914852,0.0,21,21
17,Nico Hülkenberg,Force India,1473.327035,1482.557841,72.0,9,21
18,Kimi Räikkönen,Ferrari,1468.089352,1481.710653,186.0,6,21
19,Felipe Massa,Williams,1461.671716,1485.399263,53.0,11,21
20,Jolyon Palmer,Renault,1456.028500,1472.482586,1.0,18,21
21,Felipe Nasr,Sauber,1452.099078,1468.716786,2.0,17,21
22,Jenson Button,McLaren,1450.582832,1475.078122,21.0,15,21
23,Daniil Kvyat,Toro Rosso,1432.876029,1450.245293,25.0,14,21
24,Rio Haryanto,Manor Marussia,1427.262381,1461.967005,0.0,24,12

## 2017

In [39]:
elo_standings(2017)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,Sebastian Vettel,Ferrari,1553.086416,1543.160110,317.0,2.0,20
2,Nico Hülkenberg,Renault,1539.742453,1527.793854,43.0,10.0,20
3,Sergio Pérez,Force India,1535.151557,1533.397838,100.0,7.0,20
4,Felipe Massa,Williams,1532.847864,1523.071884,43.0,11.0,19
5,Lewis Hamilton,Mercedes,1525.479611,1518.920974,363.0,1.0,20
6,Fernando Alonso,McLaren,1513.559394,1509.957329,17.0,15.0,19
7,Paul di Resta,Williams,1496.483174,1496.483174,0.0,NaN,1
8,Jenson Button,McLaren,1496.384941,1496.384941,0.0,NaN,1
9,Romain Grosjean,Haas F1 Team,1493.695924,1493.098914,28.0,13.0,20
10,Brendon Hartley,Toro Rosso,1493.200188,1490.672879,0.0,23.0,4
11,Valtteri Bottas,Mercedes,1490.078972,1487.737692,305.0,3.0,20
12,Pierre Gasly,Toro Rosso,1488.749524,1494.620740,0.0,21.0,5
13,Pascal Wehrlein,Sauber,1487.359683,1497.855412,5.0,18.0,18
14,Max Verstappen,Red Bull,1486.974744,1488.872578,168.0,6.0,20
15,Daniel Ricciardo,Red Bull,1481.058388,1494.569724,200.0,5.0,20
16,Kevin Magnussen,Haas F1 Team,1477.507616,1495.537898,19.0,14.0,20
17,Antonio Giovinazzi,Sauber,1474.829242,1485.628991,0.0,22.0,2
18,Carlos Sainz,Toro Rosso,1474.016186,1493.612753,54.0,9.0,20
19,Esteban Ocon,Force India,1468.065757,1472.694324,87.0,8.0,20
20,Daniil Kvyat,Toro Rosso,1461.271581,1477.693046,5.0,19.0,15
21,Marcus Ericsson,Sauber,1461.041415,1486.218974,0.0,20.0,20
22,Lance Stroll,Williams,1439.537347,1452.170451,40.0,12.0,20
23,Kimi Räikkönen,Ferrari,1429.160864,1450.667395,205.0,4.0,20
24,Jolyon Palmer,Renault,1426.757024,1447.666014,8.0,17.0,16
25,Stoffel Vandoorne,McLaren,1411.650572,1454.171065,13.0,16.0,20

## 2018

In [40]:
elo_standings(2018)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,Lewis Hamilton,Mercedes,1578.040596,1531.278987,408.0,1,21
2,Max Verstappen,Red Bull,1538.023629,1509.666735,249.0,4,21
3,Fernando Alonso,McLaren,1533.327008,1537.775270,50.0,11,21
4,Sebastian Vettel,Ferrari,1527.312099,1517.418151,320.0,2,21
5,Charles Leclerc,Sauber,1508.139762,1501.077675,39.0,13,21
6,Pierre Gasly,Toro Rosso,1500.824188,1500.569035,29.0,15,21
7,Kimi Räikkönen,Ferrari,1496.438106,1494.785004,251.0,3,21
8,Esteban Ocon,Force India,1494.480214,1504.222401,49.0,12,21
9,Kevin Magnussen,Haas F1 Team,1481.748131,1514.760487,56.0,9,21
10,Carlos Sainz,Renault,1481.264983,1484.271852,53.0,10,21
11,Nico Hülkenberg,Renault,1477.720133,1495.961406,69.0,7,21
12,Sergio Pérez,Force India,1475.257746,1479.122381,62.0,8,21
13,Sergey Sirotkin,Williams,1473.584413,1479.541970,1.0,20,21
14,Lance Stroll,Williams,1472.758699,1489.496133,6.0,18,21
15,Romain Grosjean,Haas F1 Team,1464.610629,1457.976330,37.0,14,21
16,Daniel Ricciardo,Red Bull,1461.795545,1484.394214,170.0,6,21
17,Valtteri Bottas,Mercedes,1447.133901,1479.976292,247.0,5,21
18,Brendon Hartley,Toro Rosso,1442.679988,1457.742834,4.0,19,21
19,Marcus Ericsson,Sauber,1424.621477,1467.451888,9.0,17,21
20,Stoffel Vandoorne,McLaren,1421.041566,1445.629003,12.0,16,21

## 2019

In [41]:
elo_standings(2019)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,George Russell,Williams,1571.332103,1548.695835,0.0,20,21
2,Max Verstappen,Red Bull,1563.727766,1543.299298,278.0,3,21
3,Lewis Hamilton,Mercedes,1549.063827,1531.180664,413.0,1,21
4,Sergio Pérez,Racing Point,1542.661171,1525.941364,52.0,10,21
5,Kimi Räikkönen,Alfa Romeo,1531.246747,1529.117675,43.0,12,21
6,Carlos Sainz,McLaren,1517.491323,1509.648930,96.0,6,21
7,Daniel Ricciardo,Renault,1504.508685,1504.310313,54.0,9,21
8,Sebastian Vettel,Ferrari,1498.869757,1511.957956,240.0,5,21
9,Kevin Magnussen,Haas F1 Team,1486.097200,1486.244679,20.0,16,21
10,Charles Leclerc,Ferrari,1482.254496,1481.625941,264.0,4,21
11,Lando Norris,McLaren,1478.339392,1480.800080,49.0,11,21
12,Valtteri Bottas,Mercedes,1470.615162,1482.535897,326.0,2,21
13,Daniil Kvyat,Toro Rosso,1468.479084,1488.041176,37.0,13,21
14,Romain Grosjean,Haas F1 Team,1466.887552,1492.928361,8.0,18,21
15,Alexander Albon,Toro Rosso,1463.842813,1488.737050,92.0,8,21
16,Pierre Gasly,Red Bull,1463.370817,1454.810104,95.0,7,21
17,Nico Hülkenberg,Renault,1461.870544,1481.635713,37.0,14,21
18,Lance Stroll,Racing Point,1425.411210,1451.412115,21.0,15,21
19,Antonio Giovinazzi,Alfa Romeo,1422.163738,1444.455727,14.0,17,21
20,Robert Kubica,Williams,1417.345526,1446.530352,1.0,19,21

## 2020

In [42]:
elo_standings(2020)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,Daniel Ricciardo,Renault,1550.471805,1533.325369,119.0,5,17
2,Max Verstappen,Red Bull,1550.279600,1544.132399,214.0,3,17
3,Lewis Hamilton,Mercedes,1546.344532,1528.271919,347.0,1,16
4,Sergio Pérez,Racing Point,1536.774519,1511.865622,125.0,4,15
5,Pierre Gasly,AlphaTauri,1516.057673,1510.599456,75.0,10,17
6,Kimi Räikkönen,Alfa Romeo,1513.932441,1512.645461,4.0,16,17
7,Charles Leclerc,Ferrari,1512.910031,1510.112878,98.0,8,17
8,Kevin Magnussen,Haas F1 Team,1510.934341,1498.758196,1.0,20,17
9,George Russell,Williams,1508.099388,1515.817117,3.0,18,17
10,Lando Norris,McLaren,1507.722588,1513.079469,97.0,9,17
11,Jack Aitken,Williams,1496.023173,1496.023173,0.0,22,1
12,Carlos Sainz,McLaren,1486.575208,1487.614823,105.0,6,17
13,Nico Hülkenberg,Racing Point,1485.462310,1492.614224,10.0,15,3
14,Pietro Fittipaldi,Haas F1 Team,1480.745167,1485.408598,0.0,23,2
15,Valtteri Bottas,Mercedes,1474.322125,1475.740133,223.0,2,17
16,Romain Grosjean,Haas F1 Team,1472.548973,1491.033469,2.0,19,15
17,Lance Stroll,Racing Point,1462.785229,1493.427337,75.0,11,16
18,Daniil Kvyat,AlphaTauri,1459.174529,1469.161239,32.0,14,17
19,Esteban Ocon,Renault,1455.450757,1470.279605,62.0,12,17
20,Antonio Giovinazzi,Alfa Romeo,1453.515217,1468.623565,4.0,17,17
21,Sebastian Vettel,Ferrari,1438.147167,1461.044677,33.0,13,17
22,Alexander Albon,Red Bull,1430.995364,1457.131611,105.0,7,17
23,Nicholas Latifi,Williams,1421.209658,1447.435400,0.0,21,17

## 2021

In [43]:
elo_standings(2021)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,Max Verstappen,Red Bull,1576.131513,1545.964219,395.5,1,22
2,Lewis Hamilton,Mercedes,1564.309840,1538.749550,387.5,2,22
3,Pierre Gasly,AlphaTauri,1563.488947,1542.103168,110.0,9,22
4,George Russell,Williams,1541.240880,1535.028180,16.0,15,22
5,Mick Schumacher,Haas F1 Team,1528.572893,1536.251843,0.0,19,22
6,Lando Norris,McLaren,1523.676364,1523.254958,160.0,6,22
7,Charles Leclerc,Ferrari,1517.187806,1522.765328,159.0,7,22
8,Antonio Giovinazzi,Alfa Romeo,1515.193885,1505.287863,3.0,18,22
9,Fernando Alonso,Alpine F1 Team,1504.994150,1497.037626,81.0,10,22
10,Kimi Räikkönen,Alfa Romeo,1491.787815,1489.026483,10.0,16,20
11,Esteban Ocon,Alpine F1 Team,1489.353270,1495.962181,74.0,11,22
12,Sebastian Vettel,Aston Martin,1486.956963,1492.963000,43.0,12,22
13,Carlos Sainz,Ferrari,1480.408076,1477.848582,164.5,5,22
14,Robert Kubica,Alfa Romeo,1477.878353,1483.083927,0.0,20,2
15,Lance Stroll,Aston Martin,1464.882489,1482.203973,34.0,13,22
16,Daniel Ricciardo,McLaren,1458.262958,1470.511265,115.0,8,22
17,Valtteri Bottas,Mercedes,1430.081320,1457.534646,226.0,3,22
18,Nikita Mazepin,Haas F1 Team,1406.452715,1435.892546,0.0,21,22
19,Sergio Pérez,Red Bull,1406.270989,1448.499804,190.0,4,22
20,Yuki Tsunoda,AlphaTauri,1404.267235,1441.221396,32.0,14,22
21,Nicholas Latifi,Williams,1398.517841,1433.954148,7.0,17,22

## 2022

In [44]:
elo_standings(2022)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,Max Verstappen,Red Bull,1584.348219,1546.693479,454.0,1,22
2,Lando Norris,McLaren,1558.738502,1529.628148,122.0,7,22
3,Alexander Albon,Williams,1538.001988,1522.318841,4.0,19,21
4,Lewis Hamilton,Mercedes,1511.952309,1492.672884,240.0,6,22
5,Nyck de Vries,Williams,1508.955867,1508.955867,2.0,21,1
6,Charles Leclerc,Ferrari,1507.884973,1517.574750,308.0,2,22
7,Pierre Gasly,AlphaTauri,1507.232655,1510.612200,23.0,14,22
8,Fernando Alonso,Alpine F1 Team,1503.201550,1487.656247,81.0,9,22
9,Valtteri Bottas,Alfa Romeo,1502.987591,1523.275377,49.0,10,22
10,Sebastian Vettel,Aston Martin,1502.277110,1500.703736,37.0,12,20
11,George Russell,Mercedes,1499.074211,1507.989232,275.0,4,22
12,Nico Hülkenberg,Aston Martin,1498.134079,1496.814558,0.0,22,2
13,Esteban Ocon,Alpine F1 Team,1492.814141,1504.807346,92.0,8,22
14,Lance Stroll,Aston Martin,1484.755653,1494.178948,18.0,15,22
15,Mick Schumacher,Haas F1 Team,1471.365527,1476.513454,12.0,16,22
16,Kevin Magnussen,Haas F1 Team,1468.228503,1495.020060,25.0,13,22
17,Sergio Pérez,Red Bull,1445.122349,1472.388894,305.0,3,22
18,Yuki Tsunoda,AlphaTauri,1442.817812,1466.669177,12.0,17,22
19,Guanyu Zhou,Alfa Romeo,1440.302721,1451.793565,6.0,18,22
20,Carlos Sainz,Ferrari,1439.117375,1455.216612,246.0,5,22
21,Daniel Ricciardo,McLaren,1413.300006,1459.223129,37.0,11,22
22,Nicholas Latifi,Williams,1373.426054,1431.339869,2.0,20,22

## 2023

In [45]:
elo_standings(2023)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,Max Verstappen,Red Bull,1604.886312,1552.874528,575.0,1,22
2,Alexander Albon,Williams,1588.866526,1554.765597,27.0,13,22
3,Fernando Alonso,Aston Martin,1578.250747,1552.781637,206.0,4,22
4,Lando Norris,McLaren,1555.686740,1532.345036,205.0,6,22
5,Yuki Tsunoda,AlphaTauri,1532.781046,1526.377721,17.0,14,22
6,Charles Leclerc,Ferrari,1530.567417,1511.745103,206.0,5,22
7,Lewis Hamilton,Mercedes,1528.611180,1520.866371,234.0,3,22
8,Valtteri Bottas,Alfa Romeo,1517.664351,1513.140764,10.0,15,22
9,Esteban Ocon,Alpine F1 Team,1509.445337,1506.776298,58.0,12,22
10,Nico Hülkenberg,Haas F1 Team,1504.008913,1497.182721,9.0,16,22
11,Liam Lawson,AlphaTauri,1498.989494,1503.200293,2.0,20,5
12,Pierre Gasly,Alpine F1 Team,1492.532857,1494.985053,62.0,11,22
13,George Russell,Mercedes,1489.472989,1492.564673,175.0,8,22
14,Daniel Ricciardo,AlphaTauri,1482.016224,1493.398010,6.0,17,7
15,Carlos Sainz,Ferrari,1480.341368,1489.831877,200.0,7,22
16,Nyck de Vries,AlphaTauri,1467.820316,1478.681885,0.0,22,10
17,Oscar Piastri,McLaren,1453.979064,1470.921529,97.0,9,22
18,Guanyu Zhou,Alfa Romeo,1451.734672,1472.737437,6.0,18,22
19,Kevin Magnussen,Haas F1 Team,1450.593146,1484.685125,3.0,19,22
20,Lance Stroll,Aston Martin,1427.856950,1450.932758,74.0,10,22
21,Sergio Pérez,Red Bull,1406.205631,1452.339136,285.0,2,22
22,Logan Sargeant,Williams,1390.626018,1434.580908,1.0,21,22

## 2024

In [46]:
elo_standings(2024)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,Max Verstappen,Red Bull,1606.449543,1567.506515,437.0,1,24
2,Alexander Albon,Williams,1581.695800,1555.228972,12.0,16,24
3,Fernando Alonso,Aston Martin,1557.287211,1529.182188,70.0,9,24
4,Lando Norris,McLaren,1544.776561,1529.486578,374.0,2,24
5,Yuki Tsunoda,RB F1 Team,1541.777894,1521.157985,30.0,12,24
6,George Russell,Mercedes,1538.679417,1524.802093,245.0,6,24
7,Charles Leclerc,Ferrari,1534.083437,1523.328193,356.0,3,24
8,Valtteri Bottas,Sauber,1531.773897,1523.284902,0.0,22,24
9,Nico Hülkenberg,Haas F1 Team,1527.040295,1532.625636,41.0,11,24
10,Pierre Gasly,Alpine F1 Team,1515.798135,1488.686869,42.0,10,24
11,Oliver Bearman,Haas F1 Team,1508.023819,1499.157960,7.0,18,3
12,Esteban Ocon,Alpine F1 Team,1501.318190,1511.883237,23.0,14,23
13,Franco Colapinto,Williams,1494.553708,1495.737233,5.0,19,9
14,Jack Doohan,Alpine F1 Team,1489.996544,1489.996544,0.0,24,1
15,Carlos Sainz,Ferrari,1486.726122,1490.648535,290.0,5,23
16,Daniel Ricciardo,RB F1 Team,1485.317459,1485.913847,12.0,17,18
17,Liam Lawson,RB F1 Team,1475.708510,1489.358727,4.0,21,6
18,Lewis Hamilton,Mercedes,1462.112655,1473.397405,223.0,7,24
19,Guanyu Zhou,Sauber,1458.823040,1467.437397,4.0,20,24
20,Oscar Piastri,McLaren,1446.071826,1469.323562,292.0,4,24
21,Kevin Magnussen,Haas F1 Team,1444.687546,1461.263915,16.0,15,22
22,Lance Stroll,Aston Martin,1440.052503,1472.729232,24.0,13,24
23,Logan Sargeant,Williams,1422.897547,1455.742619,0.0,23,14
24,Sergio Pérez,Red Bull,1391.397943,1434.603330,152.0,8,24

## 2025

In [47]:
elo_standings(2025)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,Max Verstappen,Red Bull,1616.963170,1568.443776,421.0,2,24
2,George Russell,Mercedes,1582.776481,1562.031882,319.0,4,24
3,Fernando Alonso,Aston Martin,1573.129208,1545.901698,56.0,10,24
4,Charles Leclerc,Ferrari,1570.125437,1536.970239,242.0,5,24
5,Isack Hadjar,RB F1 Team,1536.414653,1530.706756,51.0,12,24
6,Lando Norris,McLaren,1530.786617,1514.125353,423.0,1,24
7,Pierre Gasly,Alpine F1 Team,1527.880467,1516.904321,22.0,18,24
8,Oliver Bearman,Haas F1 Team,1525.886006,1502.137149,41.0,13,24
9,Nico Hülkenberg,Sauber,1504.890260,1498.463954,51.0,11,24
10,Alexander Albon,Williams,1497.128843,1520.224728,73.0,8,24
11,Gabriel Bortoleto,Sauber,1497.050461,1499.352670,19.0,19,24
12,Carlos Sainz,Williams,1496.265974,1482.019169,64.0,9,24
13,Oscar Piastri,McLaren,1492.690547,1502.224943,410.0,3,24
14,Jack Doohan,Alpine F1 Team,1479.558332,1487.397270,0.0,21,6
15,Esteban Ocon,Haas F1 Team,1476.155996,1497.231497,38.0,15,24
16,Franco Colapinto,Alpine F1 Team,1464.924070,1478.607445,0.0,20,18
17,Liam Lawson,RB F1 Team,1463.692731,1464.917934,38.0,14,24
18,Andrea Kimi Antonelli,Mercedes,1429.165555,1444.079981,150.0,7,24
19,Lewis Hamilton,Ferrari,1427.284547,1454.641687,156.0,6,24
20,Lance Stroll,Aston Martin,1418.692427,1449.294971,33.0,16,23
21,Yuki Tsunoda,Red Bull,1349.853761,1415.268585,33.0,17,24

## 2026

In [48]:
elo_standings(2026)

,driver,constructor,elo_season_end,elo_season_average,points,final_points_position,races_started
elo_rank,,,,,,,
1,Max Verstappen,Red Bull,1545.991817,1522.114897,112.0,6,12
2,Oliver Bearman,Haas F1 Team,1532.075725,1528.583690,18.0,13,12
3,Pierre Gasly,Alpine F1 Team,1531.483308,1521.244630,44.0,10,12
4,Andrea Kimi Antonelli,Mercedes,1529.303092,1518.463041,242.0,1,12
5,Lando Norris,McLaren,1520.848289,1502.919958,159.0,4,12
6,Fernando Alonso,Aston Martin,1518.559463,1513.442047,3.0,19,12
7,Liam Lawson,RB F1 Team,1518.103241,1514.936980,49.0,9,12
8,Lewis Hamilton,Ferrari,1514.992492,1507.630330,183.0,3,12
9,Charles Leclerc,Ferrari,1511.265999,1506.139316,155.0,5,12
10,Carlos Sainz,Williams,1509.591872,1511.028821,6.0,16,12
11,Sergio Pérez,Cadillac F1 Team,1505.326233,1506.560438,0.0,23,12
12,Yuki Tsunoda,RB F1 Team,1501.601262,1501.601262,0.0,20,1
13,Nico Hülkenberg,Audi,1500.158389,1502.057512,6.0,15,12
14,George Russell,Mercedes,1492.637280,1494.999985,183.0,2,12
15,Gabriel Bortoleto,Audi,1489.268018,1493.082378,10.0,14,12
16,Oscar Piastri,McLaren,1487.547062,1501.075381,104.0,7,12
17,Valtteri Bottas,Cadillac F1 Team,1487.278763,1489.322012,0.0,22,12
18,Alexander Albon,Williams,1480.268637,1484.218363,5.0,17,12
19,Lance Stroll,Aston Martin,1475.670448,1483.502309,0.0,21,12
20,Arvid Lindblad,RB F1 Team,1472.251419,1481.538195,23.0,11,12
21,Isack Hadjar,Red Bull,1460.502273,1481.069102,68.0,8,11
22,Esteban Ocon,Haas F1 Team,1458.878590,1466.757705,3.0,18,12
23,Franco Colapinto,Alpine F1 Team,1456.649866,1471.169421,19.0,12,12